// Code generated by scripts/gen_go_types.py from the vendored codex schema. DO NOT EDIT.
//
// Source: internal/protocol/schema/codex_app_server_protocol.v2.schemas.json
// Filter: None
//
// Regenerate: make generate-types

package schema

import "encoding/json"

// Account mirrors the upstream `Account` definition.
type Account = json.RawMessage

// AccountTokenUsageDailyBucket mirrors the upstream `AccountTokenUsageDailyBucket` definition.
type AccountTokenUsageDailyBucket struct {
	StartDate string `json:"startDate"`
	Tokens    int64  `json:"tokens"`
}

// AccountTokenUsageSummary mirrors the upstream `AccountTokenUsageSummary` definition.
type AccountTokenUsageSummary struct {
	CurrentStreakDays     int64 `json:"currentStreakDays,omitempty"`
	LifetimeTokens        int64 `json:"lifetimeTokens,omitempty"`
	LongestRunningTurnSec int64 `json:"longestRunningTurnSec,omitempty"`
	LongestStreakDays     int64 `json:"longestStreakDays,omitempty"`
	PeakDailyTokens       int64 `json:"peakDailyTokens,omitempty"`
}

// AddCreditsNudgeCreditType mirrors the upstream `AddCreditsNudgeCreditType` enum.
type AddCreditsNudgeCreditType string

const (
	AddCreditsNudgeCreditTypeCredits    AddCreditsNudgeCreditType = "credits"
	AddCreditsNudgeCreditTypeUsageLimit AddCreditsNudgeCreditType = "usage_limit"
)

// AddCreditsNudgeEmailStatus mirrors the upstream `AddCreditsNudgeEmailStatus` enum.
type AddCreditsNudgeEmailStatus string

const (
	AddCreditsNudgeEmailStatusSent           AddCreditsNudgeEmailStatus = "sent"
	AddCreditsNudgeEmailStatusCooldownActive AddCreditsNudgeEmailStatus = "cooldown_active"
)

// AllowDenyRequirement mirrors the upstream `AllowDenyRequirement` enum.
type AllowDenyRequirement string

const (
	AllowDenyRequirementAllow AllowDenyRequirement = "allow"
	AllowDenyRequirementDeny  AllowDenyRequirement = "deny"
)

// AnalyticsConfig mirrors the upstream `AnalyticsConfig` definition.
type AnalyticsConfig struct {
	Enabled bool `json:"enabled,omitempty"`
}

// AskForApproval mirrors the upstream `AskForApproval` definition.
type AskForApproval = json.RawMessage

// AutoCompactTokenLimitScope mirrors the upstream `AutoCompactTokenLimitScope` definition.
type AutoCompactTokenLimitScope = json.RawMessage

// AutoReviewRequirements mirrors the upstream `AutoReviewRequirements` definition.
type AutoReviewRequirements struct {
	IgnoreRules      []string `json:"ignoreRules,omitempty"`
	RequiredOnModels []string `json:"requiredOnModels,omitempty"`
}

// BrowserUseAccessApprovalLifetime mirrors the upstream `BrowserUseAccessApprovalLifetime` enum.
type BrowserUseAccessApprovalLifetime string

const (
	BrowserUseAccessApprovalLifetimeTurn   BrowserUseAccessApprovalLifetime = "turn"
	BrowserUseAccessApprovalLifetimeThread BrowserUseAccessApprovalLifetime = "thread"
)

// BrowserUseConfig mirrors the upstream `BrowserUseConfig` definition.
type BrowserUseConfig struct {
	AllowHistoryAccess  bool                          `json:"allow_history_access,omitempty"`
	DefaultOriginPolicy *BrowserUseOriginPolicyConfig `json:"default_origin_policy,omitempty"`
	Origins             map[string]any                `json:"origins,omitempty"`
}

// BrowserUseExtensionRequirements mirrors the upstream `BrowserUseExtensionRequirements` definition.
type BrowserUseExtensionRequirements struct {
	RequestHeaders []RequestHeader `json:"requestHeaders,omitempty"`
}

// BrowserUseOriginPolicy mirrors the upstream `BrowserUseOriginPolicy` definition.
type BrowserUseOriginPolicy struct {
	Access                 *AllowDenyRequirement             `json:"access,omitempty"`
	AccessApprovalLifetime *BrowserUseAccessApprovalLifetime `json:"accessApprovalLifetime,omitempty"`
	AutoReview             *AllowDenyRequirement             `json:"autoReview,omitempty"`
	Downloads              *AllowDenyRequirement             `json:"downloads,omitempty"`
	FullCdpAccess          *AllowDenyRequirement             `json:"fullCdpAccess,omitempty"`
	PersistentApproval     bool                              `json:"persistentApproval,omitempty"`
	Uploads                *AllowDenyRequirement             `json:"uploads,omitempty"`
}

// BrowserUseOriginPolicyConfig mirrors the upstream `BrowserUseOriginPolicyConfig` definition.
type BrowserUseOriginPolicyConfig struct {
	Access        *AllowDenyRequirement `json:"access,omitempty"`
	Downloads     *AllowDenyRequirement `json:"downloads,omitempty"`
	FullCdpAccess *AllowDenyRequirement `json:"full_cdp_access,omitempty"`
	Uploads       *AllowDenyRequirement `json:"uploads,omitempty"`
}

// BrowserUseRequirements mirrors the upstream `BrowserUseRequirements` definition.
type BrowserUseRequirements struct {
	AllowGlobalPersistentApproval bool                             `json:"allowGlobalPersistentApproval,omitempty"`
	AllowHistoryAccess            bool                             `json:"allowHistoryAccess,omitempty"`
	AllowWebmcp                   bool                             `json:"allowWebmcp,omitempty"`
	DefaultOriginPolicy           *BrowserUseOriginPolicy          `json:"defaultOriginPolicy,omitempty"`
	DisableAutoReview             bool                             `json:"disableAutoReview,omitempty"`
	Extension                     *BrowserUseExtensionRequirements `json:"extension,omitempty"`
	Origins                       map[string]any                   `json:"origins,omitempty"`
}

// CancelLoginAccountParams mirrors the upstream `CancelLoginAccountParams` definition.
type CancelLoginAccountParams struct {
	LoginID string `json:"loginId"`
}

// CancelLoginAccountResponse mirrors the upstream `CancelLoginAccountResponse` definition.
type CancelLoginAccountResponse struct {
	Status CancelLoginAccountStatus `json:"status"`
}

// CancelLoginAccountStatus mirrors the upstream `CancelLoginAccountStatus` enum.
type CancelLoginAccountStatus string

const (
	CancelLoginAccountStatusCanceled CancelLoginAccountStatus = "canceled"
	CancelLoginAccountStatusNotFound CancelLoginAccountStatus = "notFound"
)

// CliAuthCredentialsStoreMode mirrors the upstream `CliAuthCredentialsStoreMode` enum.
type CliAuthCredentialsStoreMode string

const (
	CliAuthCredentialsStoreModeFile      CliAuthCredentialsStoreMode = "file"
	CliAuthCredentialsStoreModeKeyring   CliAuthCredentialsStoreMode = "keyring"
	CliAuthCredentialsStoreModeAuto      CliAuthCredentialsStoreMode = "auto"
	CliAuthCredentialsStoreModeEphemeral CliAuthCredentialsStoreMode = "ephemeral"
)

// CollaborationMode mirrors the upstream `CollaborationMode` definition.
type CollaborationMode struct {
	Mode     ModeKind `json:"mode"`
	Settings Settings `json:"settings"`
}

// CommandExecParams mirrors the upstream `CommandExecParams` definition.
type CommandExecParams struct {
	Command            []string                 `json:"command"`
	CWD                string                   `json:"cwd,omitempty"`
	DisableOutputCap   bool                     `json:"disableOutputCap,omitempty"`
	DisableTimeout     bool                     `json:"disableTimeout,omitempty"`
	Env                map[string]any           `json:"env,omitempty"`
	OutputBytesCap     int64                    `json:"outputBytesCap,omitempty"`
	ProcessID          string                   `json:"processId,omitempty"`
	SandboxPolicy      *SandboxPolicy           `json:"sandboxPolicy,omitempty"`
	Size               *CommandExecTerminalSize `json:"size,omitempty"`
	StreamStdin        bool                     `json:"streamStdin,omitempty"`
	StreamStdoutStderr bool                     `json:"streamStdoutStderr,omitempty"`
	TimeoutMs          int64                    `json:"timeoutMs,omitempty"`
	Tty                bool                     `json:"tty,omitempty"`
}

// CommandExecResizeParams mirrors the upstream `CommandExecResizeParams` definition.
type CommandExecResizeParams struct {
	ProcessID string                  `json:"processId"`
	Size      CommandExecTerminalSize `json:"size"`
}

// CommandExecResizeResponse mirrors the upstream `CommandExecResizeResponse` definition.
type CommandExecResizeResponse = struct{}

// CommandExecResponse mirrors the upstream `CommandExecResponse` definition.
type CommandExecResponse struct {
	ExitCode int64  `json:"exitCode"`
	Stderr   string `json:"stderr"`
	Stdout   string `json:"stdout"`
}

// CommandExecTerminalSize mirrors the upstream `CommandExecTerminalSize` definition.
type CommandExecTerminalSize struct {
	Cols int64 `json:"cols"`
	Rows int64 `json:"rows"`
}

// CommandExecTerminateParams mirrors the upstream `CommandExecTerminateParams` definition.
type CommandExecTerminateParams struct {
	ProcessID string `json:"processId"`
}

// CommandExecTerminateResponse mirrors the upstream `CommandExecTerminateResponse` definition.
type CommandExecTerminateResponse = struct{}

// CommandExecWriteParams mirrors the upstream `CommandExecWriteParams` definition.
type CommandExecWriteParams struct {
	CloseStdin  bool   `json:"closeStdin,omitempty"`
	DeltaBase64 string `json:"deltaBase64,omitempty"`
	ProcessID   string `json:"processId"`
}

// CommandExecWriteResponse mirrors the upstream `CommandExecWriteResponse` definition.
type CommandExecWriteResponse = struct{}

// CommandMigration mirrors the upstream `CommandMigration` definition.
type CommandMigration struct {
	Name string `json:"name"`
}

// ComputerUseConfig mirrors the upstream `ComputerUseConfig` definition.
type ComputerUseConfig struct {
	DefaultAppAccess *AllowDenyRequirement     `json:"default_app_access,omitempty"`
	Macos            *ComputerUseMacosConfig   `json:"macos,omitempty"`
	Windows          *ComputerUseWindowsConfig `json:"windows,omitempty"`
}

// ComputerUseMacosConfig mirrors the upstream `ComputerUseMacosConfig` definition.
type ComputerUseMacosConfig struct {
	BundleIDs map[string]any `json:"bundle_ids,omitempty"`
}

// ComputerUseMacosRequirements mirrors the upstream `ComputerUseMacosRequirements` definition.
type ComputerUseMacosRequirements struct {
	BundleIDs map[string]any `json:"bundleIds,omitempty"`
}

// ComputerUseRequirements mirrors the upstream `ComputerUseRequirements` definition.
type ComputerUseRequirements struct {
	AllowLockedComputerUse  bool                            `json:"allowLockedComputerUse,omitempty"`
	AllowPersistentApproval bool                            `json:"allowPersistentApproval,omitempty"`
	DefaultAppAccess        *AllowDenyRequirement           `json:"defaultAppAccess,omitempty"`
	Macos                   *ComputerUseMacosRequirements   `json:"macos,omitempty"`
	Windows                 *ComputerUseWindowsRequirements `json:"windows,omitempty"`
}

// ComputerUseWindowsConfig mirrors the upstream `ComputerUseWindowsConfig` definition.
type ComputerUseWindowsConfig struct {
	Aumids map[string]any                `json:"aumids,omitempty"`
	Exes   []ComputerUseWindowsExeConfig `json:"exes,omitempty"`
}

// ComputerUseWindowsExeConfig mirrors the upstream `ComputerUseWindowsExeConfig` definition.
type ComputerUseWindowsExeConfig struct {
	Access        AllowDenyRequirement `json:"access"`
	BinaryName    string               `json:"binary_name,omitempty"`
	ProductName   string               `json:"product_name"`
	PublisherName string               `json:"publisher_name"`
}

// ComputerUseWindowsExeRequirement mirrors the upstream `ComputerUseWindowsExeRequirement` definition.
type ComputerUseWindowsExeRequirement struct {
	Access        AllowDenyRequirement `json:"access"`
	BinaryName    string               `json:"binaryName,omitempty"`
	ProductName   string               `json:"productName"`
	PublisherName string               `json:"publisherName"`
}

// ComputerUseWindowsRequirements mirrors the upstream `ComputerUseWindowsRequirements` definition.
type ComputerUseWindowsRequirements struct {
	Aumids map[string]any                     `json:"aumids,omitempty"`
	Exes   []ComputerUseWindowsExeRequirement `json:"exes,omitempty"`
}

// Config mirrors the upstream `Config` definition.
type Config struct {
	Analytics                       *AnalyticsConfig            `json:"analytics,omitempty"`
	ApprovalPolicy                  *AskForApproval             `json:"approval_policy,omitempty"`
	ApprovalsReviewer               *ApprovalsReviewer          `json:"approvals_reviewer,omitempty"`
	BrowserUse                      *BrowserUseConfig           `json:"browser_use,omitempty"`
	CompactPrompt                   string                      `json:"compact_prompt,omitempty"`
	ComputerUse                     *ComputerUseConfig          `json:"computer_use,omitempty"`
	Desktop                         map[string]any              `json:"desktop,omitempty"`
	DeveloperInstructions           string                      `json:"developer_instructions,omitempty"`
	ForcedChatgptWorkspaceID        *ForcedChatgptWorkspaceIds  `json:"forced_chatgpt_workspace_id,omitempty"`
	ForcedLoginMethod               *ForcedLoginMethod          `json:"forced_login_method,omitempty"`
	Instructions                    string                      `json:"instructions,omitempty"`
	Model                           string                      `json:"model,omitempty"`
	ModelAutoCompactTokenLimit      int64                       `json:"model_auto_compact_token_limit,omitempty"`
	ModelAutoCompactTokenLimitScope *AutoCompactTokenLimitScope `json:"model_auto_compact_token_limit_scope,omitempty"`
	ModelContextWindow              int64                       `json:"model_context_window,omitempty"`
	ModelProvider                   string                      `json:"model_provider,omitempty"`
	ModelReasoningEffort            *ReasoningEffort            `json:"model_reasoning_effort,omitempty"`
	ModelReasoningSummary           *ReasoningSummary           `json:"model_reasoning_summary,omitempty"`
	ModelVerbosity                  *Verbosity                  `json:"model_verbosity,omitempty"`
	ReviewModel                     string                      `json:"review_model,omitempty"`
	SandboxMode                     *SandboxMode                `json:"sandbox_mode,omitempty"`
	SandboxWorkspaceWrite           *SandboxWorkspaceWrite      `json:"sandbox_workspace_write,omitempty"`
	ServiceTier                     string                      `json:"service_tier,omitempty"`
	Tools                           *ToolsV2                    `json:"tools,omitempty"`
	WebSearch                       *WebSearchMode              `json:"web_search,omitempty"`
}

// ConfigBatchWriteParams mirrors the upstream `ConfigBatchWriteParams` definition.
type ConfigBatchWriteParams struct {
	Edits            []ConfigEdit `json:"edits"`
	ExpectedVersion  string       `json:"expectedVersion,omitempty"`
	FilePath         string       `json:"filePath,omitempty"`
	ReloadUserConfig bool         `json:"reloadUserConfig,omitempty"`
}

// ConfigEdit mirrors the upstream `ConfigEdit` definition.
type ConfigEdit struct {
	KeyPath       string          `json:"keyPath"`
	MergeStrategy MergeStrategy   `json:"mergeStrategy"`
	Value         json.RawMessage `json:"value"`
}

// ConfigLayer mirrors the upstream `ConfigLayer` definition.
type ConfigLayer struct {
	Config         json.RawMessage   `json:"config"`
	DisabledReason string            `json:"disabledReason,omitempty"`
	Name           ConfigLayerSource `json:"name"`
	Version        string            `json:"version"`
}

// ConfigLayerMetadata mirrors the upstream `ConfigLayerMetadata` definition.
type ConfigLayerMetadata struct {
	Name    ConfigLayerSource `json:"name"`
	Version string            `json:"version"`
}

// ConfigLayerSource mirrors the upstream `ConfigLayerSource` definition.
type ConfigLayerSource = json.RawMessage

// ConfigReadParams mirrors the upstream `ConfigReadParams` definition.
type ConfigReadParams struct {
	CWD           string `json:"cwd,omitempty"`
	IncludeLayers bool   `json:"includeLayers,omitempty"`
}

// ConfigReadResponse mirrors the upstream `ConfigReadResponse` definition.
type ConfigReadResponse struct {
	Config  Config         `json:"config"`
	Layers  []ConfigLayer  `json:"layers,omitempty"`
	Origins map[string]any `json:"origins"`
}

// ConfigRequirements mirrors the upstream `ConfigRequirements` definition.
type ConfigRequirements struct {
	AdditionalDeveloperInstructions      string                         `json:"additionalDeveloperInstructions,omitempty"`
	AllowAppshots                        bool                           `json:"allowAppshots,omitempty"`
	AllowBrowserAndComputerUse           bool                           `json:"allowBrowserAndComputerUse,omitempty"`
	AllowLoginShell                      bool                           `json:"allowLoginShell,omitempty"`
	AllowManagedHooksOnly                bool                           `json:"allowManagedHooksOnly,omitempty"`
	AllowRemoteControl                   bool                           `json:"allowRemoteControl,omitempty"`
	AllowedApprovalPolicies              []AskForApproval               `json:"allowedApprovalPolicies,omitempty"`
	AllowedLoginMethods                  []ForcedLoginMethod            `json:"allowedLoginMethods,omitempty"`
	AllowedPermissionProfiles            map[string]any                 `json:"allowedPermissionProfiles,omitempty"`
	AllowedSandboxModes                  []SandboxMode                  `json:"allowedSandboxModes,omitempty"`
	AllowedWebSearchModes                []WebSearchMode                `json:"allowedWebSearchModes,omitempty"`
	AllowedWindowsSandboxImplementations []WindowsSandboxImplementation `json:"allowedWindowsSandboxImplementations,omitempty"`
	AutoReview                           *AutoReviewRequirements        `json:"autoReview,omitempty"`
	BrowserUse                           *BrowserUseRequirements        `json:"browserUse,omitempty"`
	ChatgptBaseURL                       string                         `json:"chatgptBaseUrl,omitempty"`
	CheckForUpdateOnStartup              bool                           `json:"checkForUpdateOnStartup,omitempty"`
	CliAuthCredentialsStore              *CliAuthCredentialsStoreMode   `json:"cliAuthCredentialsStore,omitempty"`
	ComputerUse                          *ComputerUseRequirements       `json:"computerUse,omitempty"`
	DefaultPermissions                   string                         `json:"defaultPermissions,omitempty"`
	EnforceResidency                     *ResidencyRequirement          `json:"enforceResidency,omitempty"`
	FeatureRequirements                  map[string]any                 `json:"featureRequirements,omitempty"`
	Feedback                             *FeedbackRequirements          `json:"feedback,omitempty"`
	InAppBrowser                         *InAppBrowserRequirements      `json:"inAppBrowser,omitempty"`
	LogDir                               string                         `json:"logDir,omitempty"`
	ModelCatalogJSON                     string                         `json:"modelCatalogJson,omitempty"`
	ModelProvider                        string                         `json:"modelProvider,omitempty"`
	ModelProviders                       map[string]any                 `json:"modelProviders,omitempty"`
	Models                               *ModelsRequirements            `json:"models,omitempty"`
	SqliteHome                           string                         `json:"sqliteHome,omitempty"`
}

// ConfigRequirementsReadResponse mirrors the upstream `ConfigRequirementsReadResponse` definition.
type ConfigRequirementsReadResponse struct {
	Requirements                  *ConfigRequirements `json:"requirements,omitempty"`
	SupportsIndependentSpeedModes bool                `json:"supportsIndependentSpeedModes,omitempty"`
}

// ConfigValueWriteParams mirrors the upstream `ConfigValueWriteParams` definition.
type ConfigValueWriteParams struct {
	ExpectedVersion string          `json:"expectedVersion,omitempty"`
	FilePath        string          `json:"filePath,omitempty"`
	KeyPath         string          `json:"keyPath"`
	MergeStrategy   MergeStrategy   `json:"mergeStrategy"`
	Value           json.RawMessage `json:"value"`
}

// ConfigWriteResponse mirrors the upstream `ConfigWriteResponse` definition.
type ConfigWriteResponse struct {
	FilePath           AbsolutePathBuf     `json:"filePath"`
	OverriddenMetadata *OverriddenMetadata `json:"overriddenMetadata,omitempty"`
	Status             WriteStatus         `json:"status"`
	Version            string              `json:"version"`
}

// ConsumeAccountRateLimitResetCreditOutcome mirrors the upstream `ConsumeAccountRateLimitResetCreditOutcome` definition.
type ConsumeAccountRateLimitResetCreditOutcome = json.RawMessage

// ConsumeAccountRateLimitResetCreditParams mirrors the upstream `ConsumeAccountRateLimitResetCreditParams` definition.
type ConsumeAccountRateLimitResetCreditParams struct {
	CreditID       string `json:"creditId,omitempty"`
	IdempotencyKey string `json:"idempotencyKey"`
}

// ConsumeAccountRateLimitResetCreditResponse mirrors the upstream `ConsumeAccountRateLimitResetCreditResponse` definition.
type ConsumeAccountRateLimitResetCreditResponse struct {
	Outcome ConsumeAccountRateLimitResetCreditOutcome `json:"outcome"`
}

// CreditsSnapshot mirrors the upstream `CreditsSnapshot` definition.
type CreditsSnapshot struct {
	Balance    string `json:"balance,omitempty"`
	HasCredits bool   `json:"hasCredits"`
	Unlimited  bool   `json:"unlimited"`
}

// CyberAccessProgram mirrors the upstream `CyberAccessProgram` enum.
type CyberAccessProgram string

const (
	CyberAccessProgramStandard     CyberAccessProgram = "standard"
	CyberAccessProgramDaybreakBlue CyberAccessProgram = "daybreakBlue"
	CyberAccessProgramDaybreakRed  CyberAccessProgram = "daybreakRed"
)

// ExperimentalFeature mirrors the upstream `ExperimentalFeature` definition.
type ExperimentalFeature struct {
	Announcement   string                   `json:"announcement,omitempty"`
	DefaultEnabled bool                     `json:"defaultEnabled"`
	Description    string                   `json:"description,omitempty"`
	DisplayName    string                   `json:"displayName,omitempty"`
	Enabled        bool                     `json:"enabled"`
	Name           string                   `json:"name"`
	Stage          ExperimentalFeatureStage `json:"stage"`
}

// ExperimentalFeatureEnablementSetParams mirrors the upstream `ExperimentalFeatureEnablementSetParams` definition.
type ExperimentalFeatureEnablementSetParams struct {
	Enablement map[string]any `json:"enablement"`
}

// ExperimentalFeatureEnablementSetResponse mirrors the upstream `ExperimentalFeatureEnablementSetResponse` definition.
type ExperimentalFeatureEnablementSetResponse struct {
	Enablement map[string]any `json:"enablement"`
}

// ExperimentalFeatureListParams mirrors the upstream `ExperimentalFeatureListParams` definition.
type ExperimentalFeatureListParams struct {
	Cursor   string `json:"cursor,omitempty"`
	Limit    int64  `json:"limit,omitempty"`
	ThreadID string `json:"threadId,omitempty"`
}

// ExperimentalFeatureListResponse mirrors the upstream `ExperimentalFeatureListResponse` definition.
type ExperimentalFeatureListResponse struct {
	Data       []ExperimentalFeature `json:"data"`
	NextCursor string                `json:"nextCursor,omitempty"`
}

// ExperimentalFeatureStage mirrors the upstream `ExperimentalFeatureStage` definition.
type ExperimentalFeatureStage = json.RawMessage

// ExternalAgentConfigDetectParams mirrors the upstream `ExternalAgentConfigDetectParams` definition.
type ExternalAgentConfigDetectParams struct {
	Cwds              []string `json:"cwds,omitempty"`
	IncludeHome       bool     `json:"includeHome,omitempty"`
	MaxSessionAgeDays int64    `json:"maxSessionAgeDays,omitempty"`
	MaxSessions       int64    `json:"maxSessions,omitempty"`
	MigrationSource   string   `json:"migrationSource,omitempty"`
	Source            string   `json:"source,omitempty"`
}

// ExternalAgentConfigDetectResponse mirrors the upstream `ExternalAgentConfigDetectResponse` definition.
type ExternalAgentConfigDetectResponse struct {
	Connectors []ExternalAgentDetectedConnectorCandidate `json:"connectors,omitempty"`
	Items      []ExternalAgentConfigMigrationItem        `json:"items"`
}

// ExternalAgentConfigImportHistoriesReadResponse mirrors the upstream `ExternalAgentConfigImportHistoriesReadResponse` definition.
type ExternalAgentConfigImportHistoriesReadResponse struct {
	Connectors []ExternalAgentImportedConnectorCandidate `json:"connectors"`
	Data       []ExternalAgentConfigImportHistory        `json:"data"`
}

// ExternalAgentConfigImportHistory mirrors the upstream `ExternalAgentConfigImportHistory` definition.
type ExternalAgentConfigImportHistory struct {
	CompletedAtMs int64                                      `json:"completedAtMs"`
	Failures      []ExternalAgentConfigImportItemTypeFailure `json:"failures"`
	ImportID      string                                     `json:"importId"`
	ProviderID    string                                     `json:"providerId,omitempty"`
	Successes     []ExternalAgentConfigImportItemTypeSuccess `json:"successes"`
}

// ExternalAgentConfigImportHistoryRecordParams mirrors the upstream `ExternalAgentConfigImportHistoryRecordParams` definition.
type ExternalAgentConfigImportHistoryRecordParams struct {
	ItemTypeResults []ExternalAgentConfigImportHistoryRecordTypeResultParams `json:"itemTypeResults"`
	ProviderID      string                                                   `json:"providerId"`
}

// ExternalAgentConfigImportHistoryRecordResponse mirrors the upstream `ExternalAgentConfigImportHistoryRecordResponse` definition.
type ExternalAgentConfigImportHistoryRecordResponse struct {
	ImportID string `json:"importId"`
}

// ExternalAgentConfigImportHistoryRecordSuccessParams mirrors the upstream `ExternalAgentConfigImportHistoryRecordSuccessParams` definition.
type ExternalAgentConfigImportHistoryRecordSuccessParams struct {
	CWD      string                               `json:"cwd,omitempty"`
	ItemType ExternalAgentConfigMigrationItemType `json:"itemType"`
	Source   string                               `json:"source,omitempty"`
	Target   string                               `json:"target,omitempty"`
	Title    string                               `json:"title,omitempty"`
}

// ExternalAgentConfigImportHistoryRecordTypeResultParams mirrors the upstream `ExternalAgentConfigImportHistoryRecordTypeResultParams` definition.
type ExternalAgentConfigImportHistoryRecordTypeResultParams struct {
	Failures  []ExternalAgentConfigImportItemTypeFailure            `json:"failures"`
	ItemType  ExternalAgentConfigMigrationItemType                  `json:"itemType"`
	Successes []ExternalAgentConfigImportHistoryRecordSuccessParams `json:"successes"`
}

// ExternalAgentConfigImportItemTypeFailure mirrors the upstream `ExternalAgentConfigImportItemTypeFailure` definition.
type ExternalAgentConfigImportItemTypeFailure struct {
	CWD          string                               `json:"cwd,omitempty"`
	ErrorType    string                               `json:"errorType,omitempty"`
	FailureStage string                               `json:"failureStage"`
	ItemType     ExternalAgentConfigMigrationItemType `json:"itemType"`
	Message      string                               `json:"message"`
	Source       string                               `json:"source,omitempty"`
	SubErrorType string                               `json:"subErrorType,omitempty"`
}

// ExternalAgentConfigImportItemTypeSuccess mirrors the upstream `ExternalAgentConfigImportItemTypeSuccess` definition.
type ExternalAgentConfigImportItemTypeSuccess struct {
	CWD      string                               `json:"cwd,omitempty"`
	ItemType ExternalAgentConfigMigrationItemType `json:"itemType"`
	Source   string                               `json:"source,omitempty"`
	Target   string                               `json:"target,omitempty"`
	Title    string                               `json:"title,omitempty"`
}

// ExternalAgentConfigImportParams mirrors the upstream `ExternalAgentConfigImportParams` definition.
type ExternalAgentConfigImportParams struct {
	MigrationItems  []ExternalAgentConfigMigrationItem `json:"migrationItems"`
	MigrationSource string                             `json:"migrationSource,omitempty"`
	ProviderID      string                             `json:"providerId,omitempty"`
	Source          string                             `json:"source,omitempty"`
}

// ExternalAgentConfigImportResponse mirrors the upstream `ExternalAgentConfigImportResponse` definition.
type ExternalAgentConfigImportResponse struct {
	ImportID string `json:"importId"`
}

// ExternalAgentConfigMigrationItem mirrors the upstream `ExternalAgentConfigMigrationItem` definition.
type ExternalAgentConfigMigrationItem struct {
	CWD         string                               `json:"cwd,omitempty"`
	Description string                               `json:"description"`
	Details     *MigrationDetails                    `json:"details,omitempty"`
	ItemType    ExternalAgentConfigMigrationItemType `json:"itemType"`
}

// ExternalAgentConfigMigrationItemType mirrors the upstream `ExternalAgentConfigMigrationItemType` enum.
type ExternalAgentConfigMigrationItemType string

const (
	ExternalAgentConfigMigrationItemTypeAGENTSMD        ExternalAgentConfigMigrationItemType = "AGENTS_MD"
	ExternalAgentConfigMigrationItemTypeCONFIG          ExternalAgentConfigMigrationItemType = "CONFIG"
	ExternalAgentConfigMigrationItemTypeSKILLS          ExternalAgentConfigMigrationItemType = "SKILLS"
	ExternalAgentConfigMigrationItemTypePLUGINS         ExternalAgentConfigMigrationItemType = "PLUGINS"
	ExternalAgentConfigMigrationItemTypeMCPSERVERCONFIG ExternalAgentConfigMigrationItemType = "MCP_SERVER_CONFIG"
	ExternalAgentConfigMigrationItemTypeSUBAGENTS       ExternalAgentConfigMigrationItemType = "SUBAGENTS"
	ExternalAgentConfigMigrationItemTypeHOOKS           ExternalAgentConfigMigrationItemType = "HOOKS"
	ExternalAgentConfigMigrationItemTypeCOMMANDS        ExternalAgentConfigMigrationItemType = "COMMANDS"
	ExternalAgentConfigMigrationItemTypeMEMORY          ExternalAgentConfigMigrationItemType = "MEMORY"
	ExternalAgentConfigMigrationItemTypeSESSIONS        ExternalAgentConfigMigrationItemType = "SESSIONS"
)

// ExternalAgentDetectedConnectorCandidate mirrors the upstream `ExternalAgentDetectedConnectorCandidate` definition.
type ExternalAgentDetectedConnectorCandidate struct {
	Name         string                               `json:"name"`
	SessionCount int64                                `json:"sessionCount"`
	Source       ExternalAgentDetectedConnectorSource `json:"source"`
}

// ExternalAgentDetectedConnectorSource mirrors the upstream `ExternalAgentDetectedConnectorSource` enum.
type ExternalAgentDetectedConnectorSource string

const (
	ExternalAgentDetectedConnectorSourceRemoteMcpServersConfig ExternalAgentDetectedConnectorSource = "remoteMcpServersConfig"
	ExternalAgentDetectedConnectorSourceSessionToolUse         ExternalAgentDetectedConnectorSource = "sessionToolUse"
)

// ExternalAgentImportedConnectorCandidate mirrors the upstream `ExternalAgentImportedConnectorCandidate` definition.
type ExternalAgentImportedConnectorCandidate struct {
	Name         string                               `json:"name"`
	SessionCount int64                                `json:"sessionCount"`
	Source       ExternalAgentImportedConnectorSource `json:"source"`
}

// ExternalAgentImportedConnectorSource mirrors the upstream `ExternalAgentImportedConnectorSource` enum.
type ExternalAgentImportedConnectorSource string

const (
	ExternalAgentImportedConnectorSourceRemoteMcpServersConfig ExternalAgentImportedConnectorSource = "remoteMcpServersConfig"
)

// FeedbackRequirements mirrors the upstream `FeedbackRequirements` definition.
type FeedbackRequirements struct {
	Enabled bool `json:"enabled,omitempty"`
}

// FeedbackUploadParams mirrors the upstream `FeedbackUploadParams` definition.
type FeedbackUploadParams struct {
	Classification string         `json:"classification"`
	ExtraLogFiles  []string       `json:"extraLogFiles,omitempty"`
	IncludeLogs    bool           `json:"includeLogs,omitempty"`
	Reason         string         `json:"reason,omitempty"`
	Tags           map[string]any `json:"tags,omitempty"`
	ThreadID       string         `json:"threadId,omitempty"`
}

// FeedbackUploadResponse mirrors the upstream `FeedbackUploadResponse` definition.
type FeedbackUploadResponse struct {
	PromptHash string `json:"promptHash,omitempty"`
	ThreadID   string `json:"threadId"`
}

// ForcedChatgptWorkspaceIds mirrors the upstream `ForcedChatgptWorkspaceIds` definition.
type ForcedChatgptWorkspaceIds = json.RawMessage

// ForcedLoginMethod mirrors the upstream `ForcedLoginMethod` enum.
type ForcedLoginMethod string

const (
	ForcedLoginMethodChatgpt ForcedLoginMethod = "chatgpt"
	ForcedLoginMethodAPI     ForcedLoginMethod = "api"
)

// FuzzyFileSearchParams mirrors the upstream `FuzzyFileSearchParams` definition.
type FuzzyFileSearchParams struct {
	CancellationToken string   `json:"cancellationToken,omitempty"`
	Query             string   `json:"query"`
	Roots             []string `json:"roots"`
}

// GatewayOAuthCancelResponse mirrors the upstream `GatewayOAuthCancelResponse` definition.
type GatewayOAuthCancelResponse = struct{}

// GatewayOAuthLoginResponse mirrors the upstream `GatewayOAuthLoginResponse` definition.
type GatewayOAuthLoginResponse = struct{}

// GatewayOAuthReadResponse mirrors the upstream `GatewayOAuthReadResponse` definition.
type GatewayOAuthReadResponse struct {
	Error        string              `json:"error,omitempty"`
	ProviderID   string              `json:"providerId"`
	ProviderName string              `json:"providerName"`
	Required     bool                `json:"required"`
	Status       *GatewayOAuthStatus `json:"status,omitempty"`
}

// GatewayOAuthStatus mirrors the upstream `GatewayOAuthStatus` enum.
type GatewayOAuthStatus string

const (
	GatewayOAuthStatusNotReady  GatewayOAuthStatus = "notReady"
	GatewayOAuthStatusStarted   GatewayOAuthStatus = "started"
	GatewayOAuthStatusSucceeded GatewayOAuthStatus = "succeeded"
	GatewayOAuthStatusFailed    GatewayOAuthStatus = "failed"
)

// GetAccountParams mirrors the upstream `GetAccountParams` definition.
type GetAccountParams struct {
	RefreshToken bool `json:"refreshToken,omitempty"`
}

// GetAccountRateLimitsParams mirrors the upstream `GetAccountRateLimitsParams` definition.
type GetAccountRateLimitsParams struct {
	ExcludeResetCreditDetails bool `json:"excludeResetCreditDetails,omitempty"`
	SupportsLunaReserve       bool `json:"supportsLunaReserve,omitempty"`
}

// GetAccountRateLimitsResponse mirrors the upstream `GetAccountRateLimitsResponse` definition.
type GetAccountRateLimitsResponse struct {
	AccountID             string                        `json:"accountId,omitempty"`
	OrdinaryUsageAllowed  bool                          `json:"ordinaryUsageAllowed,omitempty"`
	RateLimitResetCredits *RateLimitResetCreditsSummary `json:"rateLimitResetCredits,omitempty"`
	RateLimitUpsell       json.RawMessage               `json:"rateLimitUpsell,omitempty"`
	RateLimits            RateLimitSnapshot             `json:"rateLimits"`
	RateLimitsByLimitID   map[string]any                `json:"rateLimitsByLimitId,omitempty"`
}

// GetAccountResponse mirrors the upstream `GetAccountResponse` definition.
type GetAccountResponse struct {
	Account            *Account `json:"account,omitempty"`
	RequiresOpenaiAuth bool     `json:"requiresOpenaiAuth"`
}

// GetAccountTokenUsageParams mirrors the upstream `GetAccountTokenUsageParams` definition.
type GetAccountTokenUsageParams struct {
	ThreadID string `json:"threadId,omitempty"`
}

// GetAccountTokenUsageResponse mirrors the upstream `GetAccountTokenUsageResponse` definition.
type GetAccountTokenUsageResponse struct {
	DailyUsageBuckets []AccountTokenUsageDailyBucket `json:"dailyUsageBuckets,omitempty"`
	Summary           AccountTokenUsageSummary       `json:"summary"`
	ThreadUsage       *ThreadUsage                   `json:"threadUsage,omitempty"`
}

// GetWorkspaceMessagesResponse mirrors the upstream `GetWorkspaceMessagesResponse` definition.
type GetWorkspaceMessagesResponse struct {
	FeatureEnabled bool               `json:"featureEnabled"`
	Messages       []WorkspaceMessage `json:"messages"`
}

// HookErrorInfo mirrors the upstream `HookErrorInfo` definition.
type HookErrorInfo struct {
	Message string `json:"message"`
	Path    string `json:"path"`
}

// HookMetadata mirrors the upstream `HookMetadata` definition.
type HookMetadata struct {
	AdditionalContextLimit int64           `json:"additionalContextLimit,omitempty"`
	CurrentHash            string          `json:"currentHash"`
	DisplayOrder           int64           `json:"displayOrder"`
	Enabled                bool            `json:"enabled"`
	EventName              HookEventName   `json:"eventName"`
	IsManaged              bool            `json:"isManaged"`
	Key                    string          `json:"key"`
	Matcher                string          `json:"matcher,omitempty"`
	PluginID               string          `json:"pluginId,omitempty"`
	Source                 HookSource      `json:"source"`
	SourcePath             AbsolutePathBuf `json:"sourcePath"`
	StatusMessage          string          `json:"statusMessage,omitempty"`
	TimeoutSec             int64           `json:"timeoutSec"`
	TrustStatus            HookTrustStatus `json:"trustStatus"`
}

// HookMigration mirrors the upstream `HookMigration` definition.
type HookMigration struct {
	Name string `json:"name"`
}

// HookSource mirrors the upstream `HookSource` enum.
type HookSource string

const (
	HookSourceSystem                  HookSource = "system"
	HookSourceUser                    HookSource = "user"
	HookSourceProject                 HookSource = "project"
	HookSourceMdm                     HookSource = "mdm"
	HookSourceSessionFlags            HookSource = "sessionFlags"
	HookSourcePlugin                  HookSource = "plugin"
	HookSourceCloudRequirements       HookSource = "cloudRequirements"
	HookSourceCloudManagedConfig      HookSource = "cloudManagedConfig"
	HookSourceLegacyManagedConfigFile HookSource = "legacyManagedConfigFile"
	HookSourceLegacyManagedConfigMdm  HookSource = "legacyManagedConfigMdm"
	HookSourceUnknown                 HookSource = "unknown"
)

// HookTrustStatus mirrors the upstream `HookTrustStatus` enum.
type HookTrustStatus string

const (
	HookTrustStatusManaged   HookTrustStatus = "managed"
	HookTrustStatusUntrusted HookTrustStatus = "untrusted"
	HookTrustStatusTrusted   HookTrustStatus = "trusted"
	HookTrustStatusModified  HookTrustStatus = "modified"
)

// HooksListEntry mirrors the upstream `HooksListEntry` definition.
type HooksListEntry struct {
	CWD      string          `json:"cwd"`
	Errors   []HookErrorInfo `json:"errors"`
	Hooks    []HookMetadata  `json:"hooks"`
	Warnings []string        `json:"warnings"`
}

// HooksListParams mirrors the upstream `HooksListParams` definition.
type HooksListParams struct {
	Cwds []string `json:"cwds,omitempty"`
}

// HooksListResponse mirrors the upstream `HooksListResponse` definition.
type HooksListResponse struct {
	Data []HooksListEntry `json:"data"`
}

// InAppBrowserRequirements mirrors the upstream `InAppBrowserRequirements` definition.
type InAppBrowserRequirements struct {
	AllowExternalBrowserSettingsImport bool `json:"allowExternalBrowserSettingsImport,omitempty"`
}

// InputModality mirrors the upstream `InputModality` definition.
type InputModality = json.RawMessage

// LegacyAppPathString mirrors the upstream `LegacyAppPathString` definition.
type LegacyAppPathString = string

// LoginAccountParams mirrors the upstream `LoginAccountParams` definition.
type LoginAccountParams = json.RawMessage

// LoginAccountResponse mirrors the upstream `LoginAccountResponse` definition.
type LoginAccountResponse = json.RawMessage

// LoginAppBrand mirrors the upstream `LoginAppBrand` enum.
type LoginAppBrand string

const (
	LoginAppBrandCodex   LoginAppBrand = "codex"
	LoginAppBrandChatgpt LoginAppBrand = "chatgpt"
)

// LogoutAccountResponse mirrors the upstream `LogoutAccountResponse` definition.
type LogoutAccountResponse = struct{}

// MergeStrategy mirrors the upstream `MergeStrategy` enum.
type MergeStrategy string

const (
	MergeStrategyReplace MergeStrategy = "replace"
	MergeStrategyUpsert  MergeStrategy = "upsert"
)

// MigrationDetails mirrors the upstream `MigrationDetails` definition.
type MigrationDetails struct {
	Commands   []CommandMigration   `json:"commands,omitempty"`
	Hooks      []HookMigration      `json:"hooks,omitempty"`
	McpServers []McpServerMigration `json:"mcpServers,omitempty"`
	Memory     []string             `json:"memory,omitempty"`
	Plugins    []PluginsMigration   `json:"plugins,omitempty"`
	Sessions   []SessionMigration   `json:"sessions,omitempty"`
	Skills     []SkillMigration     `json:"skills,omitempty"`
	Subagents  []SubagentMigration  `json:"subagents,omitempty"`
}

// ModeKind mirrors the upstream `ModeKind` enum.
type ModeKind string

const (
	ModeKindPlan    ModeKind = "plan"
	ModeKindDefault ModeKind = "default"
)

// Model mirrors the upstream `Model` definition.
type Model struct {
	AdditionalSpeedTiers      []string                `json:"additionalSpeedTiers,omitempty"`
	AvailabilityNux           *ModelAvailabilityNux   `json:"availabilityNux,omitempty"`
	AvailableAccessPrograms   *ModelAccessPrograms    `json:"availableAccessPrograms,omitempty"`
	DefaultReasoningEffort    ReasoningEffort         `json:"defaultReasoningEffort"`
	DefaultServiceTier        string                  `json:"defaultServiceTier,omitempty"`
	Description               string                  `json:"description"`
	DisplayName               string                  `json:"displayName"`
	Hidden                    bool                    `json:"hidden"`
	ID                        string                  `json:"id"`
	InputModalities           []InputModality         `json:"inputModalities,omitempty"`
	IsDefault                 bool                    `json:"isDefault"`
	Model                     string                  `json:"model"`
	ModelSpecialty            string                  `json:"modelSpecialty,omitempty"`
	MultiAgentVersion         *MultiAgentVersion      `json:"multiAgentVersion,omitempty"`
	ServiceTiers              []ModelServiceTier      `json:"serviceTiers,omitempty"`
	SupportedReasoningEfforts []ReasoningEffortOption `json:"supportedReasoningEfforts"`
	SupportsPersonality       bool                    `json:"supportsPersonality,omitempty"`
	Upgrade                   string                  `json:"upgrade,omitempty"`
	UpgradeInfo               *ModelUpgradeInfo       `json:"upgradeInfo,omitempty"`
}

// ModelAccessPrograms mirrors the upstream `ModelAccessPrograms` definition.
type ModelAccessPrograms struct {
	Cyber []CyberAccessProgram `json:"cyber"`
}

// ModelAvailabilityNux mirrors the upstream `ModelAvailabilityNux` definition.
type ModelAvailabilityNux struct {
	Message string `json:"message"`
}

// ModelListParams mirrors the upstream `ModelListParams` definition.
type ModelListParams struct {
	Cursor        string `json:"cursor,omitempty"`
	IncludeHidden bool   `json:"includeHidden,omitempty"`
	Limit         int64  `json:"limit,omitempty"`
}

// ModelListResponse mirrors the upstream `ModelListResponse` definition.
type ModelListResponse struct {
	Data       []Model `json:"data"`
	NextCursor string  `json:"nextCursor,omitempty"`
}

// ModelProviderCapabilitiesReadParams mirrors the upstream `ModelProviderCapabilitiesReadParams` definition.
type ModelProviderCapabilitiesReadParams = struct{}

// ModelProviderCapabilitiesReadResponse mirrors the upstream `ModelProviderCapabilitiesReadResponse` definition.
type ModelProviderCapabilitiesReadResponse struct {
	ImageGeneration bool `json:"imageGeneration"`
	WebSearch       bool `json:"webSearch"`
}

// ModelServiceTier mirrors the upstream `ModelServiceTier` definition.
type ModelServiceTier struct {
	Description string `json:"description"`
	ID          string `json:"id"`
	Name        string `json:"name"`
}

// ModelUpgradeInfo mirrors the upstream `ModelUpgradeInfo` definition.
type ModelUpgradeInfo struct {
	MigrationMarkdown string `json:"migrationMarkdown,omitempty"`
	Model             string `json:"model"`
	ModelLink         string `json:"modelLink,omitempty"`
	RetirementAt      int64  `json:"retirementAt,omitempty"`
	UpgradeCopy       string `json:"upgradeCopy,omitempty"`
}

// ModelsRequirements mirrors the upstream `ModelsRequirements` definition.
type ModelsRequirements struct {
	NewThread *NewThreadModelDefaults `json:"newThread,omitempty"`
}

// MultiAgentVersion mirrors the upstream `MultiAgentVersion` enum.
type MultiAgentVersion string

const (
	MultiAgentVersionDisabled MultiAgentVersion = "disabled"
	MultiAgentVersionV1       MultiAgentVersion = "v1"
	MultiAgentVersionV2       MultiAgentVersion = "v2"
)

// NetworkAccess mirrors the upstream `NetworkAccess` enum.
type NetworkAccess string

const (
	NetworkAccessRestricted NetworkAccess = "restricted"
	NetworkAccessEnabled    NetworkAccess = "enabled"
)

// NewThreadModelDefaults mirrors the upstream `NewThreadModelDefaults` definition.
type NewThreadModelDefaults struct {
	Model                string           `json:"model,omitempty"`
	ModelReasoningEffort *ReasoningEffort `json:"modelReasoningEffort,omitempty"`
	ServiceTier          string           `json:"serviceTier,omitempty"`
}

// NullableGetAccountRateLimitsParams mirrors the upstream `NullableGetAccountRateLimitsParams` definition.
type NullableGetAccountRateLimitsParams = *GetAccountRateLimitsParams

// NullableGetAccountTokenUsageParams mirrors the upstream `NullableGetAccountTokenUsageParams` definition.
type NullableGetAccountTokenUsageParams = *GetAccountTokenUsageParams

// OverriddenMetadata mirrors the upstream `OverriddenMetadata` definition.
type OverriddenMetadata struct {
	EffectiveValue  json.RawMessage     `json:"effectiveValue"`
	Message         string              `json:"message"`
	OverridingLayer ConfigLayerMetadata `json:"overridingLayer"`
}

// PermissionProfileListParams mirrors the upstream `PermissionProfileListParams` definition.
type PermissionProfileListParams struct {
	Cursor string `json:"cursor,omitempty"`
	CWD    string `json:"cwd,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
}

// PermissionProfileListResponse mirrors the upstream `PermissionProfileListResponse` definition.
type PermissionProfileListResponse struct {
	Data       []PermissionProfileSummary `json:"data"`
	NextCursor string                     `json:"nextCursor,omitempty"`
}

// PermissionProfileSummary mirrors the upstream `PermissionProfileSummary` definition.
type PermissionProfileSummary struct {
	Allowed     bool   `json:"allowed"`
	Description string `json:"description,omitempty"`
	ID          string `json:"id"`
}

// PlanType mirrors the upstream `PlanType` enum.
type PlanType string

const (
	PlanTypeFree                        PlanType = "free"
	PlanTypeGo                          PlanType = "go"
	PlanTypePlus                        PlanType = "plus"
	PlanTypePro                         PlanType = "pro"
	PlanTypeProlite                     PlanType = "prolite"
	PlanTypePromax                      PlanType = "promax"
	PlanTypeTeam                        PlanType = "team"
	PlanTypeSelfServeBusinessProlite    PlanType = "self_serve_business_prolite"
	PlanTypeSelfServeBusinessUsageBased PlanType = "self_serve_business_usage_based"
	PlanTypeBusiness                    PlanType = "business"
	PlanTypeEnt26                       PlanType = "ent26"
	PlanTypeEnterpriseCbpAutomation     PlanType = "enterprise_cbp_automation"
	PlanTypeEnterpriseCbpUsageBased     PlanType = "enterprise_cbp_usage_based"
	PlanTypeEnterprise                  PlanType = "enterprise"
	PlanTypeEdu                         PlanType = "edu"
	PlanTypeEduPlus                     PlanType = "edu_plus"
	PlanTypeEduPro                      PlanType = "edu_pro"
	PlanTypeUnknown                     PlanType = "unknown"
)

// RateLimitReachedType mirrors the upstream `RateLimitReachedType` enum.
type RateLimitReachedType string

const (
	RateLimitReachedTypeRateLimitReached                 RateLimitReachedType = "rate_limit_reached"
	RateLimitReachedTypeWorkspaceOwnerCreditsDepleted    RateLimitReachedType = "workspace_owner_credits_depleted"
	RateLimitReachedTypeWorkspaceMemberCreditsDepleted   RateLimitReachedType = "workspace_member_credits_depleted"
	RateLimitReachedTypeWorkspaceOwnerUsageLimitReached  RateLimitReachedType = "workspace_owner_usage_limit_reached"
	RateLimitReachedTypeWorkspaceMemberUsageLimitReached RateLimitReachedType = "workspace_member_usage_limit_reached"
)

// RateLimitResetCredit mirrors the upstream `RateLimitResetCredit` definition.
type RateLimitResetCredit struct {
	Description string                     `json:"description,omitempty"`
	ExpiresAt   int64                      `json:"expiresAt,omitempty"`
	GrantedAt   int64                      `json:"grantedAt"`
	ID          string                     `json:"id"`
	ResetType   RateLimitResetType         `json:"resetType"`
	Status      RateLimitResetCreditStatus `json:"status"`
	Title       string                     `json:"title,omitempty"`
}

// RateLimitResetCreditStatus mirrors the upstream `RateLimitResetCreditStatus` enum.
type RateLimitResetCreditStatus string

const (
	RateLimitResetCreditStatusAvailable RateLimitResetCreditStatus = "available"
	RateLimitResetCreditStatusRedeeming RateLimitResetCreditStatus = "redeeming"
	RateLimitResetCreditStatusRedeemed  RateLimitResetCreditStatus = "redeemed"
	RateLimitResetCreditStatusUnknown   RateLimitResetCreditStatus = "unknown"
)

// RateLimitResetCreditsSummary mirrors the upstream `RateLimitResetCreditsSummary` definition.
type RateLimitResetCreditsSummary struct {
	AvailableCount int64                  `json:"availableCount"`
	Credits        []RateLimitResetCredit `json:"credits,omitempty"`
}

// RateLimitResetType mirrors the upstream `RateLimitResetType` enum.
type RateLimitResetType string

const (
	RateLimitResetTypeCodexRateLimits RateLimitResetType = "codexRateLimits"
	RateLimitResetTypeUnknown         RateLimitResetType = "unknown"
)

// RateLimitSnapshot mirrors the upstream `RateLimitSnapshot` definition.
type RateLimitSnapshot struct {
	Credits              *CreditsSnapshot           `json:"credits,omitempty"`
	IndividualLimit      *SpendControlLimitSnapshot `json:"individualLimit,omitempty"`
	LimitID              string                     `json:"limitId,omitempty"`
	LimitName            string                     `json:"limitName,omitempty"`
	NormalModelSlug      string                     `json:"normalModelSlug,omitempty"`
	PlanType             *PlanType                  `json:"planType,omitempty"`
	Primary              *RateLimitWindow           `json:"primary,omitempty"`
	RateLimitReachedType *RateLimitReachedType      `json:"rateLimitReachedType,omitempty"`
	Secondary            *RateLimitWindow           `json:"secondary,omitempty"`
	SpendControlReached  bool                       `json:"spendControlReached,omitempty"`
}

// RateLimitWindow mirrors the upstream `RateLimitWindow` definition.
type RateLimitWindow struct {
	ResetsAt           int64 `json:"resetsAt,omitempty"`
	UsedPercent        int64 `json:"usedPercent"`
	WindowDurationMins int64 `json:"windowDurationMins,omitempty"`
}

// ReasoningEffort mirrors the upstream `ReasoningEffort` definition.
type ReasoningEffort = string

// ReasoningEffortOption mirrors the upstream `ReasoningEffortOption` definition.
type ReasoningEffortOption struct {
	Description     string          `json:"description"`
	ReasoningEffort ReasoningEffort `json:"reasoningEffort"`
}

// ReasoningSummary mirrors the upstream `ReasoningSummary` definition.
type ReasoningSummary = json.RawMessage

// RequestHeader mirrors the upstream `RequestHeader` definition.
type RequestHeader struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// ResidencyRequirement mirrors the upstream `ResidencyRequirement` enum.
type ResidencyRequirement string

const (
	ResidencyRequirementUs ResidencyRequirement = "us"
)

// ReviewStartResponse mirrors the upstream `ReviewStartResponse` definition.
type ReviewStartResponse struct {
	ReviewThreadID string `json:"reviewThreadId"`
	Turn           Turn   `json:"turn"`
}

// SandboxMode mirrors the upstream `SandboxMode` enum.
type SandboxMode string

const (
	SandboxModeReadOnly         SandboxMode = "read-only"
	SandboxModeWorkspaceWrite   SandboxMode = "workspace-write"
	SandboxModeDangerFullAccess SandboxMode = "danger-full-access"
)

// SandboxPolicy mirrors the upstream `SandboxPolicy` definition.
type SandboxPolicy = json.RawMessage

// SandboxWorkspaceWrite mirrors the upstream `SandboxWorkspaceWrite` definition.
type SandboxWorkspaceWrite struct {
	ExcludeSlashTmp     bool     `json:"exclude_slash_tmp,omitempty"`
	ExcludeTmpdirEnvVar bool     `json:"exclude_tmpdir_env_var,omitempty"`
	NetworkAccess       bool     `json:"network_access,omitempty"`
	WritableRoots       []string `json:"writable_roots,omitempty"`
}

// SendAddCreditsNudgeEmailParams mirrors the upstream `SendAddCreditsNudgeEmailParams` definition.
type SendAddCreditsNudgeEmailParams struct {
	CreditType AddCreditsNudgeCreditType `json:"creditType"`
}

// SendAddCreditsNudgeEmailResponse mirrors the upstream `SendAddCreditsNudgeEmailResponse` definition.
type SendAddCreditsNudgeEmailResponse struct {
	Status AddCreditsNudgeEmailStatus `json:"status"`
}

// SessionMigration mirrors the upstream `SessionMigration` definition.
type SessionMigration struct {
	CWD   string `json:"cwd"`
	Path  string `json:"path"`
	Title string `json:"title,omitempty"`
}

// Settings mirrors the upstream `Settings` definition.
type Settings struct {
	DeveloperInstructions string           `json:"developer_instructions,omitempty"`
	Model                 string           `json:"model"`
	ReasoningEffort       *ReasoningEffort `json:"reasoning_effort,omitempty"`
}

// SkillMigration mirrors the upstream `SkillMigration` definition.
type SkillMigration struct {
	Name string `json:"name"`
}

// SortDirection mirrors the upstream `SortDirection` enum.
type SortDirection string

const (
	SortDirectionAsc  SortDirection = "asc"
	SortDirectionDesc SortDirection = "desc"
)

// SpendControlLimitSnapshot mirrors the upstream `SpendControlLimitSnapshot` definition.
type SpendControlLimitSnapshot struct {
	Limit            string `json:"limit"`
	RemainingPercent int64  `json:"remainingPercent"`
	ResetsAt         int64  `json:"resetsAt"`
	Used             string `json:"used"`
}

// SubagentMigration mirrors the upstream `SubagentMigration` definition.
type SubagentMigration struct {
	Name string `json:"name"`
}

// ThreadApproveGuardianDeniedActionParams mirrors the upstream `ThreadApproveGuardianDeniedActionParams` definition.
type ThreadApproveGuardianDeniedActionParams struct {
	Event    json.RawMessage `json:"event"`
	ThreadID string          `json:"threadId"`
}

// ThreadApproveGuardianDeniedActionResponse mirrors the upstream `ThreadApproveGuardianDeniedActionResponse` definition.
type ThreadApproveGuardianDeniedActionResponse = struct{}

// ThreadArchiveResponse mirrors the upstream `ThreadArchiveResponse` definition.
type ThreadArchiveResponse = struct{}

// ThreadAttachment mirrors the upstream `ThreadAttachment` definition.
type ThreadAttachment struct {
	AttachmentType string          `json:"attachmentType"`
	CreatedAt      int64           `json:"createdAt"`
	ID             string          `json:"id"`
	IdentityKey    string          `json:"identityKey"`
	Payload        json.RawMessage `json:"payload"`
}

// ThreadAttachmentAddOutcome mirrors the upstream `ThreadAttachmentAddOutcome` enum.
type ThreadAttachmentAddOutcome string

const (
	ThreadAttachmentAddOutcomeCreated  ThreadAttachmentAddOutcome = "created"
	ThreadAttachmentAddOutcomeExisting ThreadAttachmentAddOutcome = "existing"
)

// ThreadAttachmentAddParams mirrors the upstream `ThreadAttachmentAddParams` definition.
type ThreadAttachmentAddParams struct {
	AttachmentType string          `json:"attachmentType"`
	IdentityKey    string          `json:"identityKey"`
	Payload        json.RawMessage `json:"payload"`
	ThreadID       string          `json:"threadId"`
}

// ThreadAttachmentAddResponse mirrors the upstream `ThreadAttachmentAddResponse` definition.
type ThreadAttachmentAddResponse struct {
	Attachment ThreadAttachment           `json:"attachment"`
	Outcome    ThreadAttachmentAddOutcome `json:"outcome"`
}

// ThreadAttachmentListParams mirrors the upstream `ThreadAttachmentListParams` definition.
type ThreadAttachmentListParams struct {
	Cursor   string `json:"cursor,omitempty"`
	Limit    int64  `json:"limit,omitempty"`
	ThreadID string `json:"threadId"`
}

// ThreadAttachmentListResponse mirrors the upstream `ThreadAttachmentListResponse` definition.
type ThreadAttachmentListResponse struct {
	Data       []ThreadAttachment `json:"data"`
	NextCursor string             `json:"nextCursor,omitempty"`
}

// ThreadAttachmentOwner mirrors the upstream `ThreadAttachmentOwner` definition.
type ThreadAttachmentOwner struct {
	Archived bool   `json:"archived"`
	ThreadID string `json:"threadId"`
}

// ThreadAttachmentOwnerListParams mirrors the upstream `ThreadAttachmentOwnerListParams` definition.
type ThreadAttachmentOwnerListParams struct {
	Archived       bool   `json:"archived,omitempty"`
	AttachmentType string `json:"attachmentType"`
	Cursor         string `json:"cursor,omitempty"`
	IdentityKey    string `json:"identityKey"`
	Limit          int64  `json:"limit,omitempty"`
}

// ThreadAttachmentOwnerListResponse mirrors the upstream `ThreadAttachmentOwnerListResponse` definition.
type ThreadAttachmentOwnerListResponse struct {
	Data       []ThreadAttachmentOwner `json:"data"`
	NextCursor string                  `json:"nextCursor,omitempty"`
}

// ThreadAttachmentRemoveParams mirrors the upstream `ThreadAttachmentRemoveParams` definition.
type ThreadAttachmentRemoveParams struct {
	AttachmentType string `json:"attachmentType"`
	IdentityKey    string `json:"identityKey"`
	ThreadID       string `json:"threadId"`
}

// ThreadAttachmentRemoveResponse mirrors the upstream `ThreadAttachmentRemoveResponse` definition.
type ThreadAttachmentRemoveResponse = struct{}

// ThreadCompactStartParams mirrors the upstream `ThreadCompactStartParams` definition.
type ThreadCompactStartParams struct {
	ThreadID string `json:"threadId"`
}

// ThreadCompactStartResponse mirrors the upstream `ThreadCompactStartResponse` definition.
type ThreadCompactStartResponse = struct{}

// ThreadDeleteParams mirrors the upstream `ThreadDeleteParams` definition.
type ThreadDeleteParams struct {
	ThreadID string `json:"threadId"`
}

// ThreadDeleteResponse mirrors the upstream `ThreadDeleteResponse` definition.
type ThreadDeleteResponse = struct{}

// ThreadInjectItemsParams mirrors the upstream `ThreadInjectItemsParams` definition.
type ThreadInjectItemsParams struct {
	Items    []json.RawMessage `json:"items"`
	ThreadID string            `json:"threadId"`
}

// ThreadInjectItemsResponse mirrors the upstream `ThreadInjectItemsResponse` definition.
type ThreadInjectItemsResponse = struct{}

// ThreadItemEntry mirrors the upstream `ThreadItemEntry` definition.
type ThreadItemEntry struct {
	CompletedAtMs int64      `json:"completedAtMs,omitempty"`
	Item          ThreadItem `json:"item"`
	StartedAtMs   int64      `json:"startedAtMs,omitempty"`
	TurnID        string     `json:"turnId"`
}

// ThreadItemsListAnchor mirrors the upstream `ThreadItemsListAnchor` definition.
type ThreadItemsListAnchor = map[string]any

// ThreadItemsListCursor mirrors the upstream `ThreadItemsListCursor` definition.
type ThreadItemsListCursor = json.RawMessage

// ThreadItemsListParams mirrors the upstream `ThreadItemsListParams` definition.
type ThreadItemsListParams struct {
	Cursor        *ThreadItemsListCursor `json:"cursor,omitempty"`
	Limit         int64                  `json:"limit,omitempty"`
	SortDirection *SortDirection         `json:"sortDirection,omitempty"`
	ThreadID      string                 `json:"threadId"`
	TurnID        string                 `json:"turnId,omitempty"`
}

// ThreadItemsListResponse mirrors the upstream `ThreadItemsListResponse` definition.
type ThreadItemsListResponse struct {
	BackwardsCursor string            `json:"backwardsCursor,omitempty"`
	Data            []ThreadItemEntry `json:"data"`
	NextCursor      string            `json:"nextCursor,omitempty"`
}

// ThreadLoadedListParams mirrors the upstream `ThreadLoadedListParams` definition.
type ThreadLoadedListParams struct {
	Cursor string `json:"cursor,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
}

// ThreadLoadedListResponse mirrors the upstream `ThreadLoadedListResponse` definition.
type ThreadLoadedListResponse struct {
	Data       []string `json:"data"`
	NextCursor string   `json:"nextCursor,omitempty"`
}

// ThreadMetadataGitInfoUpdateParams mirrors the upstream `ThreadMetadataGitInfoUpdateParams` definition.
type ThreadMetadataGitInfoUpdateParams struct {
	Branch    string `json:"branch,omitempty"`
	OriginURL string `json:"originUrl,omitempty"`
	Sha       string `json:"sha,omitempty"`
}

// ThreadMetadataUpdateParams mirrors the upstream `ThreadMetadataUpdateParams` definition.
type ThreadMetadataUpdateParams struct {
	GitInfo  *ThreadMetadataGitInfoUpdateParams `json:"gitInfo,omitempty"`
	ThreadID string                             `json:"threadId"`
}

// ThreadMetadataUpdateResponse mirrors the upstream `ThreadMetadataUpdateResponse` definition.
type ThreadMetadataUpdateResponse struct {
	Thread Thread `json:"thread"`
}

// ThreadReadResponse mirrors the upstream `ThreadReadResponse` definition.
type ThreadReadResponse struct {
	Thread Thread `json:"thread"`
}

// ThreadResumeResponse mirrors the upstream `ThreadResumeResponse` definition.
type ThreadResumeResponse struct {
	ApprovalPolicy       AskForApproval        `json:"approvalPolicy"`
	ApprovalsReviewer    ApprovalsReviewer     `json:"approvalsReviewer"`
	CollaborationMode    *CollaborationMode    `json:"collaborationMode,omitempty"`
	CWD                  AbsolutePathBuf       `json:"cwd"`
	DisabledPluginIDs    []string              `json:"disabledPluginIds,omitempty"`
	InstructionSources   []LegacyAppPathString `json:"instructionSources,omitempty"`
	ItemsBackwardsCursor string                `json:"itemsBackwardsCursor,omitempty"`
	Model                string                `json:"model"`
	ModelProvider        string                `json:"modelProvider"`
	ReasoningEffort      *ReasoningEffort      `json:"reasoningEffort,omitempty"`
	Sandbox              SandboxPolicy         `json:"sandbox"`
	ServiceTier          string                `json:"serviceTier,omitempty"`
	Thread               Thread                `json:"thread"`
	TurnsBackwardsCursor string                `json:"turnsBackwardsCursor,omitempty"`
}

// ThreadSection mirrors the upstream `ThreadSection` definition.
type ThreadSection struct {
	Appearance *ThreadSectionAppearance `json:"appearance,omitempty"`
	ID         string                   `json:"id"`
	Name       string                   `json:"name"`
}

// ThreadSectionAppearance mirrors the upstream `ThreadSectionAppearance` definition.
type ThreadSectionAppearance struct {
	Color string `json:"color,omitempty"`
	Icon  string `json:"icon,omitempty"`
}

// ThreadSectionCreateParams mirrors the upstream `ThreadSectionCreateParams` definition.
type ThreadSectionCreateParams struct {
	Appearance *ThreadSectionAppearance `json:"appearance,omitempty"`
	Name       string                   `json:"name"`
}

// ThreadSectionCreateResponse mirrors the upstream `ThreadSectionCreateResponse` definition.
type ThreadSectionCreateResponse struct {
	Section ThreadSection `json:"section"`
}

// ThreadSectionDeleteParams mirrors the upstream `ThreadSectionDeleteParams` definition.
type ThreadSectionDeleteParams struct {
	SectionID string `json:"sectionId"`
}

// ThreadSectionDeleteResponse mirrors the upstream `ThreadSectionDeleteResponse` definition.
type ThreadSectionDeleteResponse = struct{}

// ThreadSectionListParams mirrors the upstream `ThreadSectionListParams` definition.
type ThreadSectionListParams struct {
	Cursor string `json:"cursor,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
}

// ThreadSectionListResponse mirrors the upstream `ThreadSectionListResponse` definition.
type ThreadSectionListResponse struct {
	Data       []ThreadSection `json:"data"`
	NextCursor string          `json:"nextCursor,omitempty"`
}

// ThreadSectionMoveParams mirrors the upstream `ThreadSectionMoveParams` definition.
type ThreadSectionMoveParams struct {
	BeforeThreadID string `json:"beforeThreadId,omitempty"`
	SectionID      string `json:"sectionId"`
	ThreadID       string `json:"threadId"`
}

// ThreadSectionMoveResponse mirrors the upstream `ThreadSectionMoveResponse` definition.
type ThreadSectionMoveResponse = struct{}

// ThreadSectionUpdateParams mirrors the upstream `ThreadSectionUpdateParams` definition.
type ThreadSectionUpdateParams struct {
	Appearance *ThreadSectionAppearance `json:"appearance,omitempty"`
	Name       string                   `json:"name"`
	SectionID  string                   `json:"sectionId"`
}

// ThreadSectionUpdateResponse mirrors the upstream `ThreadSectionUpdateResponse` definition.
type ThreadSectionUpdateResponse struct {
	Section ThreadSection `json:"section"`
}

// ThreadSetNameResponse mirrors the upstream `ThreadSetNameResponse` definition.
type ThreadSetNameResponse = struct{}

// ThreadShellCommandParams mirrors the upstream `ThreadShellCommandParams` definition.
type ThreadShellCommandParams struct {
	Command   string `json:"command"`
	ThreadID  string `json:"threadId"`
	TimeoutMs int64  `json:"timeoutMs,omitempty"`
}

// ThreadShellCommandResponse mirrors the upstream `ThreadShellCommandResponse` definition.
type ThreadShellCommandResponse = struct{}

// ThreadStartResponse mirrors the upstream `ThreadStartResponse` definition.
type ThreadStartResponse struct {
	ApprovalPolicy     AskForApproval        `json:"approvalPolicy"`
	ApprovalsReviewer  ApprovalsReviewer     `json:"approvalsReviewer"`
	CWD                AbsolutePathBuf       `json:"cwd"`
	DisabledPluginIDs  []string              `json:"disabledPluginIds,omitempty"`
	InstructionSources []LegacyAppPathString `json:"instructionSources,omitempty"`
	Model              string                `json:"model"`
	ModelProvider      string                `json:"modelProvider"`
	ReasoningEffort    *ReasoningEffort      `json:"reasoningEffort,omitempty"`
	Sandbox            SandboxPolicy         `json:"sandbox"`
	ServiceTier        string                `json:"serviceTier,omitempty"`
	Thread             Thread                `json:"thread"`
}

// ThreadTurnsListParams mirrors the upstream `ThreadTurnsListParams` definition.
type ThreadTurnsListParams struct {
	Cursor        string         `json:"cursor,omitempty"`
	ItemsView     *TurnItemsView `json:"itemsView,omitempty"`
	Limit         int64          `json:"limit,omitempty"`
	SortDirection *SortDirection `json:"sortDirection,omitempty"`
	ThreadID      string         `json:"threadId"`
}

// ThreadTurnsListResponse mirrors the upstream `ThreadTurnsListResponse` definition.
type ThreadTurnsListResponse struct {
	BackwardsCursor string `json:"backwardsCursor,omitempty"`
	Data            []Turn `json:"data"`
	NextCursor      string `json:"nextCursor,omitempty"`
}

// ThreadUnarchiveResponse mirrors the upstream `ThreadUnarchiveResponse` definition.
type ThreadUnarchiveResponse struct {
	Thread Thread `json:"thread"`
}

// ThreadUnsubscribeParams mirrors the upstream `ThreadUnsubscribeParams` definition.
type ThreadUnsubscribeParams struct {
	ThreadID string `json:"threadId"`
}

// ThreadUnsubscribeResponse mirrors the upstream `ThreadUnsubscribeResponse` definition.
type ThreadUnsubscribeResponse struct {
	Status ThreadUnsubscribeStatus `json:"status"`
}

// ThreadUnsubscribeStatus mirrors the upstream `ThreadUnsubscribeStatus` enum.
type ThreadUnsubscribeStatus string

const (
	ThreadUnsubscribeStatusNotLoaded     ThreadUnsubscribeStatus = "notLoaded"
	ThreadUnsubscribeStatusNotSubscribed ThreadUnsubscribeStatus = "notSubscribed"
	ThreadUnsubscribeStatusUnsubscribed  ThreadUnsubscribeStatus = "unsubscribed"
)

// ThreadUsage mirrors the upstream `ThreadUsage` definition.
type ThreadUsage struct {
	EstimatedUsageCreditsMicros int64                       `json:"estimatedUsageCreditsMicros"`
	EstimatedUsageUsdMicros     int64                       `json:"estimatedUsageUsdMicros,omitempty"`
	Groups                      []ThreadUsageBreakdownGroup `json:"groups"`
	ThreadID                    string                      `json:"threadId"`
}

// ThreadUsageBreakdownGroup mirrors the upstream `ThreadUsageBreakdownGroup` definition.
type ThreadUsageBreakdownGroup struct {
	CachedInputTokens           int64  `json:"cachedInputTokens,omitempty"`
	EstimatedUsageCreditsMicros int64  `json:"estimatedUsageCreditsMicros"`
	InputTokens                 int64  `json:"inputTokens,omitempty"`
	Model                       string `json:"model,omitempty"`
	NetNewInputTokens           int64  `json:"netNewInputTokens,omitempty"`
	OutputTokens                int64  `json:"outputTokens,omitempty"`
	ReasoningEffort             string `json:"reasoningEffort,omitempty"`
	Speed                       string `json:"speed,omitempty"`
	TotalTokens                 int64  `json:"totalTokens,omitempty"`
}

// ToolsV2 mirrors the upstream `ToolsV2` definition.
type ToolsV2 struct {
	WebSearch *WebSearchToolConfig `json:"web_search,omitempty"`
}

// TurnInterruptResponse mirrors the upstream `TurnInterruptResponse` definition.
type TurnInterruptResponse = struct{}

// TurnStartResponse mirrors the upstream `TurnStartResponse` definition.
type TurnStartResponse struct {
	Turn Turn `json:"turn"`
}

// TurnSteerResponse mirrors the upstream `TurnSteerResponse` definition.
type TurnSteerResponse struct {
	TurnID string `json:"turnId"`
}

// Verbosity mirrors the upstream `Verbosity` enum.
type Verbosity string

const (
	VerbosityLow    Verbosity = "low"
	VerbosityMedium Verbosity = "medium"
	VerbosityHigh   Verbosity = "high"
)

// WebSearchContextSize mirrors the upstream `WebSearchContextSize` enum.
type WebSearchContextSize string

const (
	WebSearchContextSizeLow    WebSearchContextSize = "low"
	WebSearchContextSizeMedium WebSearchContextSize = "medium"
	WebSearchContextSizeHigh   WebSearchContextSize = "high"
)

// WebSearchLocation mirrors the upstream `WebSearchLocation` definition.
type WebSearchLocation struct {
	City     string `json:"city,omitempty"`
	Country  string `json:"country,omitempty"`
	Region   string `json:"region,omitempty"`
	Timezone string `json:"timezone,omitempty"`
}

// WebSearchMode mirrors the upstream `WebSearchMode` enum.
type WebSearchMode string

const (
	WebSearchModeDisabled WebSearchMode = "disabled"
	WebSearchModeCached   WebSearchMode = "cached"
	WebSearchModeIndexed  WebSearchMode = "indexed"
	WebSearchModeLive     WebSearchMode = "live"
)

// WebSearchToolConfig mirrors the upstream `WebSearchToolConfig` definition.
type WebSearchToolConfig struct {
	AllowedDomains []string              `json:"allowed_domains,omitempty"`
	ContextSize    *WebSearchContextSize `json:"context_size,omitempty"`
	Location       *WebSearchLocation    `json:"location,omitempty"`
}

// WindowsSandboxImplementation mirrors the upstream `WindowsSandboxImplementation` enum.
type WindowsSandboxImplementation string

const (
	WindowsSandboxImplementationElevated   WindowsSandboxImplementation = "elevated"
	WindowsSandboxImplementationUnelevated WindowsSandboxImplementation = "unelevated"
	WindowsSandboxImplementationMxc        WindowsSandboxImplementation = "mxc"
)

// WindowsSandboxReadiness mirrors the upstream `WindowsSandboxReadiness` enum.
type WindowsSandboxReadiness string

const (
	WindowsSandboxReadinessReady          WindowsSandboxReadiness = "ready"
	WindowsSandboxReadinessNotConfigured  WindowsSandboxReadiness = "notConfigured"
	WindowsSandboxReadinessUpdateRequired WindowsSandboxReadiness = "updateRequired"
)

// WindowsSandboxReadinessResponse mirrors the upstream `WindowsSandboxReadinessResponse` definition.
type WindowsSandboxReadinessResponse struct {
	Status WindowsSandboxReadiness `json:"status"`
}

// WindowsSandboxSetupMode mirrors the upstream `WindowsSandboxSetupMode` enum.
type WindowsSandboxSetupMode string

const (
	WindowsSandboxSetupModeElevated   WindowsSandboxSetupMode = "elevated"
	WindowsSandboxSetupModeUnelevated WindowsSandboxSetupMode = "unelevated"
)

// WindowsSandboxSetupStartParams mirrors the upstream `WindowsSandboxSetupStartParams` definition.
type WindowsSandboxSetupStartParams struct {
	CWD  *AbsolutePathBuf        `json:"cwd,omitempty"`
	Mode WindowsSandboxSetupMode `json:"mode"`
}

// WindowsSandboxSetupStartResponse mirrors the upstream `WindowsSandboxSetupStartResponse` definition.
type WindowsSandboxSetupStartResponse struct {
	Started bool `json:"started"`
}

// WorkspaceMessage mirrors the upstream `WorkspaceMessage` definition.
type WorkspaceMessage struct {
	ArchivedAt  int64                `json:"archivedAt,omitempty"`
	CreatedAt   int64                `json:"createdAt,omitempty"`
	MessageBody string               `json:"messageBody"`
	MessageID   string               `json:"messageId"`
	MessageType WorkspaceMessageType `json:"messageType"`
}

// WorkspaceMessageType mirrors the upstream `WorkspaceMessageType` enum.
type WorkspaceMessageType string

const (
	WorkspaceMessageTypeHeadline     WorkspaceMessageType = "headline"
	WorkspaceMessageTypeAnnouncement WorkspaceMessageType = "announcement"
	WorkspaceMessageTypeUnknown      WorkspaceMessageType = "unknown"
)

// WriteStatus mirrors the upstream `WriteStatus` enum.
type WriteStatus string

const (
	WriteStatusOk           WriteStatus = "ok"
	WriteStatusOkOverridden WriteStatus = "okOverridden"
)
