// Code generated by `go run ./tools/codexgen gen-types` from the vendored codex schema. DO NOT EDIT.
//
// Source: internal/protocol/schema/codex_app_server_protocol.v2.schemas.json
// Filter: ^(App|Plugin|Marketplace)
//
// Regenerate: make generate-types

package schema

import "encoding/json"

// AppBranding mirrors the upstream `AppBranding` definition.
type AppBranding struct {
	Category          string `json:"category,omitempty"`
	Developer         string `json:"developer,omitempty"`
	IsDiscoverableApp bool   `json:"isDiscoverableApp"`
	PrivacyPolicy     string `json:"privacyPolicy,omitempty"`
	TermsOfService    string `json:"termsOfService,omitempty"`
	Website           string `json:"website,omitempty"`
}

// AppConfig mirrors the upstream `AppConfig` definition.
type AppConfig struct {
	ApprovalsReviewer        *ApprovalsReviewer    `json:"approvals_reviewer,omitempty"`
	DefaultToolsApprovalMode *AppToolApproval      `json:"default_tools_approval_mode,omitempty"`
	DefaultToolsEnabled      bool                  `json:"default_tools_enabled,omitempty"`
	DestructiveEnabled       bool                  `json:"destructive_enabled,omitempty"`
	Enabled                  bool                  `json:"enabled,omitempty"`
	Links                    *AppLinksConfig       `json:"links,omitempty"`
	OmitToolsFrom            []ToolExposureSurface `json:"omit_tools_from,omitempty"`
	OpenWorldEnabled         bool                  `json:"open_world_enabled,omitempty"`
	Tools                    *AppToolsConfig       `json:"tools,omitempty"`
}

// AppInfo mirrors the upstream `AppInfo` definition.
type AppInfo struct {
	AppMetadata         *AppMetadata      `json:"appMetadata,omitempty"`
	Branding            *AppBranding      `json:"branding,omitempty"`
	Description         string            `json:"description,omitempty"`
	DistributionChannel string            `json:"distributionChannel,omitempty"`
	IconAssets          map[string]string `json:"iconAssets,omitempty"`
	IconDarkAssets      map[string]string `json:"iconDarkAssets,omitempty"`
	ID                  string            `json:"id"`
	InstallURL          string            `json:"installUrl,omitempty"`
	IsAccessible        bool              `json:"isAccessible,omitempty"`
	IsEnabled           bool              `json:"isEnabled,omitempty"`
	Labels              map[string]string `json:"labels,omitempty"`
	LogoURL             string            `json:"logoUrl,omitempty"`
	LogoURLDark         string            `json:"logoUrlDark,omitempty"`
	Name                string            `json:"name"`
	PluginDisplayNames  []string          `json:"pluginDisplayNames,omitempty"`
}

// AppLinkConfig mirrors the upstream `AppLinkConfig` definition.
type AppLinkConfig struct {
	ApprovalsReviewer        *ApprovalsReviewer `json:"approvals_reviewer,omitempty"`
	DefaultToolsApprovalMode *AppToolApproval   `json:"default_tools_approval_mode,omitempty"`
}

// AppLinksConfig mirrors the upstream `AppLinksConfig` definition.
type AppLinksConfig = struct{}

// AppListUpdatedNotification mirrors the upstream `AppListUpdatedNotification` definition.
type AppListUpdatedNotification struct {
	Data []AppInfo `json:"data"`
}

// AppMetadata mirrors the upstream `AppMetadata` definition.
type AppMetadata struct {
	Categories                 []string        `json:"categories,omitempty"`
	Developer                  string          `json:"developer,omitempty"`
	FirstPartyRequiresInstall  bool            `json:"firstPartyRequiresInstall,omitempty"`
	Review                     *AppReview      `json:"review,omitempty"`
	Screenshots                []AppScreenshot `json:"screenshots,omitempty"`
	SeoDescription             string          `json:"seoDescription,omitempty"`
	ShowInComposerWhenUnlinked bool            `json:"showInComposerWhenUnlinked,omitempty"`
	SubCategories              []string        `json:"subCategories,omitempty"`
	Version                    string          `json:"version,omitempty"`
	VersionID                  string          `json:"versionId,omitempty"`
	VersionNotes               string          `json:"versionNotes,omitempty"`
}

// AppReview mirrors the upstream `AppReview` definition.
type AppReview struct {
	Status string `json:"status"`
}

// AppScreenshot mirrors the upstream `AppScreenshot` definition.
type AppScreenshot struct {
	FileID     string `json:"fileId,omitempty"`
	URL        string `json:"url,omitempty"`
	UserPrompt string `json:"userPrompt"`
}

// AppSummary mirrors the upstream `AppSummary` definition.
type AppSummary struct {
	Category    string `json:"category,omitempty"`
	Description string `json:"description,omitempty"`
	ID          string `json:"id"`
	InstallURL  string `json:"installUrl,omitempty"`
	Name        string `json:"name"`
}

// AppTemplateSummary mirrors the upstream `AppTemplateSummary` definition.
type AppTemplateSummary struct {
	CanonicalConnectorID string                        `json:"canonicalConnectorId,omitempty"`
	Category             string                        `json:"category,omitempty"`
	Description          string                        `json:"description,omitempty"`
	LogoURL              string                        `json:"logoUrl,omitempty"`
	LogoURLDark          string                        `json:"logoUrlDark,omitempty"`
	MaterializedAppIDs   []string                      `json:"materializedAppIds"`
	Name                 string                        `json:"name"`
	Reason               *AppTemplateUnavailableReason `json:"reason,omitempty"`
	TemplateID           string                        `json:"templateId"`
}

// AppTemplateUnavailableReason mirrors the upstream `AppTemplateUnavailableReason` enum.
type AppTemplateUnavailableReason string

const (
	AppTemplateUnavailableReasonNOTCONFIGUREDFORWORKSPACE AppTemplateUnavailableReason = "NOT_CONFIGURED_FOR_WORKSPACE"
	AppTemplateUnavailableReasonNOACTIVEWORKSPACE         AppTemplateUnavailableReason = "NO_ACTIVE_WORKSPACE"
)

// AppToolApproval mirrors the upstream `AppToolApproval` enum.
type AppToolApproval string

const (
	AppToolApprovalAuto    AppToolApproval = "auto"
	AppToolApprovalPrompt  AppToolApproval = "prompt"
	AppToolApprovalWrites  AppToolApproval = "writes"
	AppToolApprovalApprove AppToolApproval = "approve"
)

// AppToolConfig mirrors the upstream `AppToolConfig` definition.
type AppToolConfig struct {
	ApprovalMode *AppToolApproval `json:"approval_mode,omitempty"`
	Enabled      bool             `json:"enabled,omitempty"`
}

// AppToolSummary mirrors the upstream `AppToolSummary` definition.
type AppToolSummary struct {
	Description    string `json:"description"`
	DisabledReason string `json:"disabledReason,omitempty"`
	IsEnabled      bool   `json:"isEnabled,omitempty"`
	IsReadOnly     bool   `json:"isReadOnly,omitempty"`
	Name           string `json:"name"`
	Title          string `json:"title,omitempty"`
}

// AppToolsConfig mirrors the upstream `AppToolsConfig` definition.
type AppToolsConfig = struct{}

// ApplicationNetworkRequirements mirrors the upstream `ApplicationNetworkRequirements` definition.
type ApplicationNetworkRequirements struct {
	Domains map[string]NetworkDomainPermission `json:"domains"`
	Enabled bool                               `json:"enabled"`
}

// ApplicationRequirements mirrors the upstream `ApplicationRequirements` definition.
type ApplicationRequirements struct {
	Network *ApplicationNetworkRequirements `json:"network,omitempty"`
}

// ApprovalsReviewer mirrors the upstream `ApprovalsReviewer` enum.
type ApprovalsReviewer string

const (
	ApprovalsReviewerUser             ApprovalsReviewer = "user"
	ApprovalsReviewerAutoReview       ApprovalsReviewer = "auto_review"
	ApprovalsReviewerGuardianSubagent ApprovalsReviewer = "guardian_subagent"
)

// AppsConfig mirrors the upstream `AppsConfig` definition.
type AppsConfig struct {
	Default *AppsDefaultConfig `json:"_default,omitempty"`
}

// AppsDefaultConfig mirrors the upstream `AppsDefaultConfig` definition.
type AppsDefaultConfig struct {
	ApprovalsReviewer        *ApprovalsReviewer `json:"approvals_reviewer,omitempty"`
	DefaultToolsApprovalMode *AppToolApproval   `json:"default_tools_approval_mode,omitempty"`
	DestructiveEnabled       bool               `json:"destructive_enabled,omitempty"`
	Enabled                  bool               `json:"enabled,omitempty"`
	OpenWorldEnabled         bool               `json:"open_world_enabled,omitempty"`
}

// AppsInstalledParams mirrors the upstream `AppsInstalledParams` definition.
type AppsInstalledParams struct {
	ForceRefresh bool   `json:"forceRefresh,omitempty"`
	ThreadID     string `json:"threadId,omitempty"`
}

// AppsInstalledResponse mirrors the upstream `AppsInstalledResponse` definition.
type AppsInstalledResponse struct {
	Apps []InstalledApp `json:"apps"`
}

// AppsListParams mirrors the upstream `AppsListParams` definition.
type AppsListParams struct {
	Cursor       string `json:"cursor,omitempty"`
	ForceRefetch bool   `json:"forceRefetch,omitempty"`
	Limit        int64  `json:"limit,omitempty"`
	ThreadID     string `json:"threadId,omitempty"`
}

// AppsListResponse mirrors the upstream `AppsListResponse` definition.
type AppsListResponse struct {
	Data       []AppInfo `json:"data"`
	NextCursor string    `json:"nextCursor,omitempty"`
}

// AppsReadParams mirrors the upstream `AppsReadParams` definition.
type AppsReadParams struct {
	AppIDs       []string `json:"appIds"`
	IncludeTools bool     `json:"includeTools,omitempty"`
	ThreadID     string   `json:"threadId,omitempty"`
}

// AppsReadResponse mirrors the upstream `AppsReadResponse` definition.
type AppsReadResponse struct {
	Apps          []ConnectorMetadata `json:"apps"`
	MissingAppIDs []string            `json:"missingAppIds"`
}

// ConnectorMetadata mirrors the upstream `ConnectorMetadata` definition.
type ConnectorMetadata struct {
	Description         string           `json:"description,omitempty"`
	DistributionChannel string           `json:"distributionChannel,omitempty"`
	IconURL             string           `json:"iconUrl,omitempty"`
	IconURLDark         string           `json:"iconUrlDark,omitempty"`
	ID                  string           `json:"id"`
	InstallURL          string           `json:"installUrl,omitempty"`
	Name                string           `json:"name"`
	PluginDisplayNames  []string         `json:"pluginDisplayNames,omitempty"`
	ToolSummaries       []AppToolSummary `json:"toolSummaries,omitempty"`
}

// HookEventName mirrors the upstream `HookEventName` enum.
type HookEventName string

const (
	HookEventNamePreToolUse        HookEventName = "preToolUse"
	HookEventNamePermissionRequest HookEventName = "permissionRequest"
	HookEventNamePostToolUse       HookEventName = "postToolUse"
	HookEventNamePreCompact        HookEventName = "preCompact"
	HookEventNamePostCompact       HookEventName = "postCompact"
	HookEventNameSessionStart      HookEventName = "sessionStart"
	HookEventNameSessionEnd        HookEventName = "sessionEnd"
	HookEventNameUserPromptSubmit  HookEventName = "userPromptSubmit"
	HookEventNameSubagentStart     HookEventName = "subagentStart"
	HookEventNameSubagentStop      HookEventName = "subagentStop"
	HookEventNameStop              HookEventName = "stop"
	HookEventNameInterrupt         HookEventName = "interrupt"
)

// InstalledApp mirrors the upstream `InstalledApp` definition.
type InstalledApp struct {
	Callable    bool   `json:"callable"`
	Enabled     bool   `json:"enabled"`
	ID          string `json:"id"`
	RuntimeName string `json:"runtimeName,omitempty"`
}

// MarketplaceAddParams mirrors the upstream `MarketplaceAddParams` definition.
type MarketplaceAddParams struct {
	RefName     string   `json:"refName,omitempty"`
	Source      string   `json:"source"`
	SparsePaths []string `json:"sparsePaths,omitempty"`
}

// MarketplaceAddResponse mirrors the upstream `MarketplaceAddResponse` definition.
type MarketplaceAddResponse struct {
	AlreadyAdded    bool            `json:"alreadyAdded"`
	InstalledRoot   AbsolutePathBuf `json:"installedRoot"`
	MarketplaceName string          `json:"marketplaceName"`
}

// MarketplaceInterface mirrors the upstream `MarketplaceInterface` definition.
type MarketplaceInterface struct {
	DisplayName string `json:"displayName,omitempty"`
}

// MarketplaceLoadErrorInfo mirrors the upstream `MarketplaceLoadErrorInfo` definition.
type MarketplaceLoadErrorInfo struct {
	MarketplacePath AbsolutePathBuf `json:"marketplacePath"`
	Message         string          `json:"message"`
}

// MarketplaceRemoveParams mirrors the upstream `MarketplaceRemoveParams` definition.
type MarketplaceRemoveParams struct {
	MarketplaceName string `json:"marketplaceName"`
}

// MarketplaceRemoveResponse mirrors the upstream `MarketplaceRemoveResponse` definition.
type MarketplaceRemoveResponse struct {
	InstalledRoot   *AbsolutePathBuf `json:"installedRoot,omitempty"`
	MarketplaceName string           `json:"marketplaceName"`
}

// MarketplaceUpgradeErrorInfo mirrors the upstream `MarketplaceUpgradeErrorInfo` definition.
type MarketplaceUpgradeErrorInfo struct {
	MarketplaceName string `json:"marketplaceName"`
	Message         string `json:"message"`
}

// MarketplaceUpgradeParams mirrors the upstream `MarketplaceUpgradeParams` definition.
type MarketplaceUpgradeParams struct {
	MarketplaceName string `json:"marketplaceName,omitempty"`
}

// MarketplaceUpgradeResponse mirrors the upstream `MarketplaceUpgradeResponse` definition.
type MarketplaceUpgradeResponse struct {
	Errors               []MarketplaceUpgradeErrorInfo `json:"errors"`
	SelectedMarketplaces []string                      `json:"selectedMarketplaces"`
	UpgradedRoots        []AbsolutePathBuf             `json:"upgradedRoots"`
}

// NetworkDomainPermission mirrors the upstream `NetworkDomainPermission` enum.
type NetworkDomainPermission string

const (
	NetworkDomainPermissionAllow NetworkDomainPermission = "allow"
	NetworkDomainPermissionDeny  NetworkDomainPermission = "deny"
)

// PluginAuthPolicy mirrors the upstream `PluginAuthPolicy` enum.
type PluginAuthPolicy string

const (
	PluginAuthPolicyONINSTALL PluginAuthPolicy = "ON_INSTALL"
	PluginAuthPolicyONUSE     PluginAuthPolicy = "ON_USE"
)

// PluginAvailability mirrors the upstream `PluginAvailability` enum.
type PluginAvailability string

const (
	PluginAvailabilityDISABLEDBYADMIN PluginAvailability = "DISABLED_BY_ADMIN"
	PluginAvailabilityAVAILABLE       PluginAvailability = "AVAILABLE"
)

// PluginDetail mirrors the upstream `PluginDetail` definition.
type PluginDetail struct {
	AppTemplates    []AppTemplateSummary   `json:"appTemplates"`
	Apps            []AppSummary           `json:"apps"`
	Description     string                 `json:"description,omitempty"`
	Hooks           []PluginHookSummary    `json:"hooks"`
	MarketplaceName string                 `json:"marketplaceName"`
	MarketplacePath *AbsolutePathBuf       `json:"marketplacePath,omitempty"`
	McpServers      []string               `json:"mcpServers"`
	OnboardingSkill *SkillSummary          `json:"onboardingSkill,omitempty"`
	ScheduledTasks  []ScheduledTaskSummary `json:"scheduledTasks,omitempty"`
	ShareURL        string                 `json:"shareUrl,omitempty"`
	Skills          []SkillSummary         `json:"skills"`
	Summary         PluginSummary          `json:"summary"`
}

// PluginDisabledReason mirrors the upstream `PluginDisabledReason` enum.
type PluginDisabledReason string

const (
	PluginDisabledReasonDisabledByAdmin        PluginDisabledReason = "disabled_by_admin"
	PluginDisabledReasonPlanNotEligible        PluginDisabledReason = "plan_not_eligible"
	PluginDisabledReasonRequiredAppUnavailable PluginDisabledReason = "required_app_unavailable"
	PluginDisabledReasonUnknown                PluginDisabledReason = "unknown"
)

// PluginHookSummary mirrors the upstream `PluginHookSummary` definition.
type PluginHookSummary struct {
	EventName HookEventName `json:"eventName"`
	Key       string        `json:"key"`
}

// PluginInstallParams mirrors the upstream `PluginInstallParams` definition.
type PluginInstallParams struct {
	InstallAttemptID      string           `json:"installAttemptId,omitempty"`
	MarketplacePath       *AbsolutePathBuf `json:"marketplacePath,omitempty"`
	PluginName            string           `json:"pluginName"`
	RemoteMarketplaceName string           `json:"remoteMarketplaceName,omitempty"`
}

// PluginInstallPolicy mirrors the upstream `PluginInstallPolicy` enum.
type PluginInstallPolicy string

const (
	PluginInstallPolicyNOTAVAILABLE       PluginInstallPolicy = "NOT_AVAILABLE"
	PluginInstallPolicyAVAILABLE          PluginInstallPolicy = "AVAILABLE"
	PluginInstallPolicyINSTALLEDBYDEFAULT PluginInstallPolicy = "INSTALLED_BY_DEFAULT"
)

// PluginInstallPolicySource mirrors the upstream `PluginInstallPolicySource` enum.
type PluginInstallPolicySource string

const (
	PluginInstallPolicySourceWORKSPACESETTING     PluginInstallPolicySource = "WORKSPACE_SETTING"
	PluginInstallPolicySourceIMPLICITCANONICALAPP PluginInstallPolicySource = "IMPLICIT_CANONICAL_APP"
)

// PluginInstallResponse mirrors the upstream `PluginInstallResponse` definition.
type PluginInstallResponse struct {
	AppsNeedingAuth []AppSummary     `json:"appsNeedingAuth"`
	AuthPolicy      PluginAuthPolicy `json:"authPolicy"`
}

// PluginInstalledParams mirrors the upstream `PluginInstalledParams` definition.
type PluginInstalledParams struct {
	Cwds                         []AbsolutePathBuf `json:"cwds,omitempty"`
	InstallSuggestionPluginNames []string          `json:"installSuggestionPluginNames,omitempty"`
}

// PluginInstalledResponse mirrors the upstream `PluginInstalledResponse` definition.
type PluginInstalledResponse struct {
	MarketplaceLoadErrors []MarketplaceLoadErrorInfo `json:"marketplaceLoadErrors,omitempty"`
	Marketplaces          []PluginMarketplaceEntry   `json:"marketplaces"`
}

// PluginInterface mirrors the upstream `PluginInterface` definition.
type PluginInterface struct {
	BrandColor        string            `json:"brandColor,omitempty"`
	Capabilities      []string          `json:"capabilities"`
	Category          string            `json:"category,omitempty"`
	ComposerIcon      *AbsolutePathBuf  `json:"composerIcon,omitempty"`
	ComposerIconURL   string            `json:"composerIconUrl,omitempty"`
	DefaultPrompt     []string          `json:"defaultPrompt,omitempty"`
	DeveloperName     string            `json:"developerName,omitempty"`
	DisplayName       string            `json:"displayName,omitempty"`
	Logo              *AbsolutePathBuf  `json:"logo,omitempty"`
	LogoDark          *AbsolutePathBuf  `json:"logoDark,omitempty"`
	LogoURL           string            `json:"logoUrl,omitempty"`
	LogoURLDark       string            `json:"logoUrlDark,omitempty"`
	LongDescription   string            `json:"longDescription,omitempty"`
	PrivacyPolicyURL  string            `json:"privacyPolicyUrl,omitempty"`
	ScreenshotURLs    []string          `json:"screenshotUrls"`
	Screenshots       []AbsolutePathBuf `json:"screenshots"`
	ShortDescription  string            `json:"shortDescription,omitempty"`
	TermsOfServiceURL string            `json:"termsOfServiceUrl,omitempty"`
	WebsiteURL        string            `json:"websiteUrl,omitempty"`
}

// PluginListMarketplaceKind mirrors the upstream `PluginListMarketplaceKind` enum.
type PluginListMarketplaceKind string

const (
	PluginListMarketplaceKindLocal              PluginListMarketplaceKind = "local"
	PluginListMarketplaceKindVertical           PluginListMarketplaceKind = "vertical"
	PluginListMarketplaceKindWorkspaceDirectory PluginListMarketplaceKind = "workspace-directory"
	PluginListMarketplaceKindSharedWithMe       PluginListMarketplaceKind = "shared-with-me"
	PluginListMarketplaceKindCreatedByMeRemote  PluginListMarketplaceKind = "created-by-me-remote"
)

// PluginListParams mirrors the upstream `PluginListParams` definition.
type PluginListParams struct {
	Cwds             []AbsolutePathBuf           `json:"cwds,omitempty"`
	ForceRefetch     bool                        `json:"forceRefetch,omitempty"`
	MarketplaceKinds []PluginListMarketplaceKind `json:"marketplaceKinds,omitempty"`
}

// PluginListResponse mirrors the upstream `PluginListResponse` definition.
type PluginListResponse struct {
	FeaturedPluginIDs     []string                   `json:"featuredPluginIds,omitempty"`
	MarketplaceLoadErrors []MarketplaceLoadErrorInfo `json:"marketplaceLoadErrors,omitempty"`
	Marketplaces          []PluginMarketplaceEntry   `json:"marketplaces"`
}

// PluginMarketplaceEntry mirrors the upstream `PluginMarketplaceEntry` definition.
type PluginMarketplaceEntry struct {
	Interface *MarketplaceInterface `json:"interface,omitempty"`
	Name      string                `json:"name"`
	Path      *AbsolutePathBuf      `json:"path,omitempty"`
	Plugins   []PluginSummary       `json:"plugins"`
}

// PluginReadParams mirrors the upstream `PluginReadParams` definition.
type PluginReadParams struct {
	MarketplacePath       *AbsolutePathBuf `json:"marketplacePath,omitempty"`
	PluginName            string           `json:"pluginName"`
	RemoteMarketplaceName string           `json:"remoteMarketplaceName,omitempty"`
}

// PluginReadResponse mirrors the upstream `PluginReadResponse` definition.
type PluginReadResponse struct {
	Plugin PluginDetail `json:"plugin"`
}

// PluginReconcileChangedPlugin mirrors the upstream `PluginReconcileChangedPlugin` definition.
type PluginReconcileChangedPlugin struct {
	HasApps   bool   `json:"hasApps"`
	HasHooks  bool   `json:"hasHooks"`
	HasMcps   bool   `json:"hasMcps"`
	HasSkills bool   `json:"hasSkills"`
	ID        string `json:"id"`
}

// PluginReconcileParams mirrors the upstream `PluginReconcileParams` definition.
type PluginReconcileParams struct {
	Reason string `json:"reason,omitempty"`
}

// PluginReconcileResponse mirrors the upstream `PluginReconcileResponse` definition.
type PluginReconcileResponse struct {
	ChangedPlugins                       []PluginReconcileChangedPlugin `json:"changedPlugins"`
	FailedMaterializationRemotePluginIDs []string                       `json:"failedMaterializationRemotePluginIds"`
	FailedRemotePluginIDs                []string                       `json:"failedRemotePluginIds"`
}

// PluginSearchResult mirrors the upstream `PluginSearchResult` definition.
type PluginSearchResult struct {
	MarketplaceName string           `json:"marketplaceName"`
	MarketplacePath *AbsolutePathBuf `json:"marketplacePath,omitempty"`
	Plugin          PluginSummary    `json:"plugin"`
}

// PluginSearchScope mirrors the upstream `PluginSearchScope` enum.
type PluginSearchScope string

const (
	PluginSearchScopeGlobal_   PluginSearchScope = "global"
	PluginSearchScopeWorkspace PluginSearchScope = "workspace"
	PluginSearchScopePersonal  PluginSearchScope = "personal"
)

// PluginShareCheckoutParams mirrors the upstream `PluginShareCheckoutParams` definition.
type PluginShareCheckoutParams struct {
	RemotePluginID string `json:"remotePluginId"`
}

// PluginShareCheckoutResponse mirrors the upstream `PluginShareCheckoutResponse` definition.
type PluginShareCheckoutResponse struct {
	MarketplaceName string          `json:"marketplaceName"`
	MarketplacePath AbsolutePathBuf `json:"marketplacePath"`
	PluginID        string          `json:"pluginId"`
	PluginName      string          `json:"pluginName"`
	PluginPath      AbsolutePathBuf `json:"pluginPath"`
	RemotePluginID  string          `json:"remotePluginId"`
	RemoteVersion   string          `json:"remoteVersion,omitempty"`
}

// PluginShareContext mirrors the upstream `PluginShareContext` definition.
type PluginShareContext struct {
	CanPublishToWorkspace bool                        `json:"canPublishToWorkspace,omitempty"`
	CreatorAccountUserID  string                      `json:"creatorAccountUserId,omitempty"`
	CreatorName           string                      `json:"creatorName,omitempty"`
	Discoverability       *PluginShareDiscoverability `json:"discoverability,omitempty"`
	RemotePluginID        string                      `json:"remotePluginId"`
	RemoteVersion         string                      `json:"remoteVersion,omitempty"`
	SharePrincipals       []PluginSharePrincipal      `json:"sharePrincipals,omitempty"`
	ShareURL              string                      `json:"shareUrl,omitempty"`
}

// PluginShareDeleteParams mirrors the upstream `PluginShareDeleteParams` definition.
type PluginShareDeleteParams struct {
	RemotePluginID string `json:"remotePluginId"`
}

// PluginShareDeleteResponse mirrors the upstream `PluginShareDeleteResponse` definition.
type PluginShareDeleteResponse = struct{}

// PluginShareDiscoverability mirrors the upstream `PluginShareDiscoverability` enum.
type PluginShareDiscoverability string

const (
	PluginShareDiscoverabilityLISTED   PluginShareDiscoverability = "LISTED"
	PluginShareDiscoverabilityUNLISTED PluginShareDiscoverability = "UNLISTED"
	PluginShareDiscoverabilityPRIVATE  PluginShareDiscoverability = "PRIVATE"
)

// PluginShareListItem mirrors the upstream `PluginShareListItem` definition.
type PluginShareListItem struct {
	LocalPluginPath *AbsolutePathBuf `json:"localPluginPath,omitempty"`
	Plugin          PluginSummary    `json:"plugin"`
}

// PluginShareListParams mirrors the upstream `PluginShareListParams` definition.
type PluginShareListParams = struct{}

// PluginShareListResponse mirrors the upstream `PluginShareListResponse` definition.
type PluginShareListResponse struct {
	Data []PluginShareListItem `json:"data"`
}

// PluginSharePrincipal mirrors the upstream `PluginSharePrincipal` definition.
type PluginSharePrincipal struct {
	Name          string                   `json:"name"`
	PrincipalID   string                   `json:"principalId"`
	PrincipalType PluginSharePrincipalType `json:"principalType"`
	Role          PluginSharePrincipalRole `json:"role"`
}

// PluginSharePrincipalRole mirrors the upstream `PluginSharePrincipalRole` enum.
type PluginSharePrincipalRole string

const (
	PluginSharePrincipalRoleReader PluginSharePrincipalRole = "reader"
	PluginSharePrincipalRoleEditor PluginSharePrincipalRole = "editor"
	PluginSharePrincipalRoleOwner  PluginSharePrincipalRole = "owner"
)

// PluginSharePrincipalType mirrors the upstream `PluginSharePrincipalType` enum.
type PluginSharePrincipalType string

const (
	PluginSharePrincipalTypeUser      PluginSharePrincipalType = "user"
	PluginSharePrincipalTypeGroup     PluginSharePrincipalType = "group"
	PluginSharePrincipalTypeWorkspace PluginSharePrincipalType = "workspace"
)

// PluginShareSaveParams mirrors the upstream `PluginShareSaveParams` definition.
type PluginShareSaveParams struct {
	Discoverability *PluginShareDiscoverability `json:"discoverability,omitempty"`
	PluginPath      AbsolutePathBuf             `json:"pluginPath"`
	RemotePluginID  string                      `json:"remotePluginId,omitempty"`
	ShareTargets    []PluginShareTarget         `json:"shareTargets,omitempty"`
}

// PluginShareSaveResponse mirrors the upstream `PluginShareSaveResponse` definition.
type PluginShareSaveResponse struct {
	CanPublishToWorkspace bool   `json:"canPublishToWorkspace,omitempty"`
	RemotePluginID        string `json:"remotePluginId"`
	ShareURL              string `json:"shareUrl"`
}

// PluginShareTarget mirrors the upstream `PluginShareTarget` definition.
type PluginShareTarget struct {
	PrincipalID   string                   `json:"principalId"`
	PrincipalType PluginSharePrincipalType `json:"principalType"`
	Role          PluginShareTargetRole    `json:"role"`
}

// PluginShareTargetRole mirrors the upstream `PluginShareTargetRole` enum.
type PluginShareTargetRole string

const (
	PluginShareTargetRoleReader PluginShareTargetRole = "reader"
	PluginShareTargetRoleEditor PluginShareTargetRole = "editor"
)

// PluginShareUpdateDiscoverability mirrors the upstream `PluginShareUpdateDiscoverability` enum.
type PluginShareUpdateDiscoverability string

const (
	PluginShareUpdateDiscoverabilityUNLISTED PluginShareUpdateDiscoverability = "UNLISTED"
	PluginShareUpdateDiscoverabilityPRIVATE  PluginShareUpdateDiscoverability = "PRIVATE"
	PluginShareUpdateDiscoverabilityLISTED   PluginShareUpdateDiscoverability = "LISTED"
)

// PluginShareUpdateTargetsParams mirrors the upstream `PluginShareUpdateTargetsParams` definition.
type PluginShareUpdateTargetsParams struct {
	Discoverability PluginShareUpdateDiscoverability `json:"discoverability"`
	RemotePluginID  string                           `json:"remotePluginId"`
	ShareTargets    []PluginShareTarget              `json:"shareTargets"`
}

// PluginShareUpdateTargetsResponse mirrors the upstream `PluginShareUpdateTargetsResponse` definition.
type PluginShareUpdateTargetsResponse struct {
	Discoverability PluginShareDiscoverability `json:"discoverability"`
	Principals      []PluginSharePrincipal     `json:"principals"`
}

// PluginSkillReadParams mirrors the upstream `PluginSkillReadParams` definition.
type PluginSkillReadParams struct {
	RemoteMarketplaceName string `json:"remoteMarketplaceName"`
	RemotePluginID        string `json:"remotePluginId"`
	SkillName             string `json:"skillName"`
}

// PluginSkillReadResponse mirrors the upstream `PluginSkillReadResponse` definition.
type PluginSkillReadResponse struct {
	Contents string `json:"contents,omitempty"`
}

// PluginSource mirrors the upstream `PluginSource` definition.
//
// Upstream declares it as a `type`-tagged union of 4 variants (git, local, npm, remote).
// It is modelled as one flat struct with an explicit Type discriminator
// plus the union of every variant's fields, so no field is dropped and no variant is
// rejected.
//
// Fields that disagree in type across variants, or that are themselves unions, are passed
// through as json.RawMessage rather than guessed at.
type PluginSource struct {
	Type     string          `json:"type"`
	Path     json.RawMessage `json:"path,omitempty"`
	RefName  string          `json:"refName,omitempty"`
	Sha      string          `json:"sha,omitempty"`
	URL      string          `json:"url,omitempty"`
	Package  string          `json:"package,omitempty"`
	Registry string          `json:"registry,omitempty"`
	Version  string          `json:"version,omitempty"`
}

// PluginSource discriminator values, matching the upstream variant tags.
const (
	PluginSourceTypeLocal  = "local"
	PluginSourceTypeGit    = "git"
	PluginSourceTypeNpm    = "npm"
	PluginSourceTypeRemote = "remote"
)

// PluginSummary mirrors the upstream `PluginSummary` definition.
type PluginSummary struct {
	AuthPolicy                       PluginAuthPolicy           `json:"authPolicy"`
	Availability                     PluginAvailability         `json:"availability,omitempty"`
	DisabledReason                   *PluginDisabledReason      `json:"disabledReason,omitempty"`
	EligiblePlanTypes                []string                   `json:"eligiblePlanTypes,omitempty"`
	Enabled                          bool                       `json:"enabled"`
	ID                               string                     `json:"id"`
	InstallPolicy                    PluginInstallPolicy        `json:"installPolicy"`
	InstallPolicySource              *PluginInstallPolicySource `json:"installPolicySource,omitempty"`
	Installed                        bool                       `json:"installed"`
	InstalledAt                      int64                      `json:"installedAt,omitempty"`
	Interface                        *PluginInterface           `json:"interface,omitempty"`
	Keywords                         []string                   `json:"keywords,omitempty"`
	LocalVersion                     string                     `json:"localVersion,omitempty"`
	MustShowInstallationInterstitial bool                       `json:"mustShowInstallationInterstitial,omitempty"`
	Name                             string                     `json:"name"`
	RemotePluginID                   string                     `json:"remotePluginId,omitempty"`
	ShareContext                     *PluginShareContext        `json:"shareContext,omitempty"`
	Source                           PluginSource               `json:"source"`
	Version                          string                     `json:"version,omitempty"`
}

// PluginUninstallParams mirrors the upstream `PluginUninstallParams` definition.
type PluginUninstallParams struct {
	PluginID string `json:"pluginId"`
}

// PluginUninstallResponse mirrors the upstream `PluginUninstallResponse` definition.
type PluginUninstallResponse = struct{}

// PluginsMigration mirrors the upstream `PluginsMigration` definition.
type PluginsMigration struct {
	MarketplaceName string   `json:"marketplaceName"`
	PluginNames     []string `json:"pluginNames"`
}

// ScheduledTaskSchedule mirrors the upstream `ScheduledTaskSchedule` definition.
//
// Upstream declares it as a `type`-tagged union of 4 variants (daily, hourly, weekdays, weekly).
// It is modelled as one flat struct with an explicit Type discriminator
// plus the union of every variant's fields, so no field is dropped and no variant is
// rejected.
//
// Fields that disagree in type across variants, or that are themselves unions, are passed
// through as json.RawMessage rather than guessed at.
type ScheduledTaskSchedule struct {
	Type          string                 `json:"type"`
	Days          []ScheduledTaskWeekday `json:"days,omitempty"`
	IntervalHours int64                  `json:"intervalHours,omitempty"`
	Time          string                 `json:"time,omitempty"`
}

// ScheduledTaskSchedule discriminator values, matching the upstream variant tags.
const (
	ScheduledTaskScheduleTypeHourly   = "hourly"
	ScheduledTaskScheduleTypeDaily    = "daily"
	ScheduledTaskScheduleTypeWeekdays = "weekdays"
	ScheduledTaskScheduleTypeWeekly   = "weekly"
)

// ScheduledTaskSummary mirrors the upstream `ScheduledTaskSummary` definition.
type ScheduledTaskSummary struct {
	Key      string                `json:"key"`
	Name     string                `json:"name"`
	Prompt   string                `json:"prompt"`
	Schedule ScheduledTaskSchedule `json:"schedule"`
}

// ScheduledTaskWeekday mirrors the upstream `ScheduledTaskWeekday` enum.
type ScheduledTaskWeekday string

const (
	ScheduledTaskWeekdayMO ScheduledTaskWeekday = "MO"
	ScheduledTaskWeekdayTU ScheduledTaskWeekday = "TU"
	ScheduledTaskWeekdayWE ScheduledTaskWeekday = "WE"
	ScheduledTaskWeekdayTH ScheduledTaskWeekday = "TH"
	ScheduledTaskWeekdayFR ScheduledTaskWeekday = "FR"
	ScheduledTaskWeekdaySA ScheduledTaskWeekday = "SA"
	ScheduledTaskWeekdaySU ScheduledTaskWeekday = "SU"
)

// SkillInterface mirrors the upstream `SkillInterface` definition.
type SkillInterface struct {
	BrandColor       string           `json:"brandColor,omitempty"`
	DefaultPrompt    string           `json:"defaultPrompt,omitempty"`
	DisplayName      string           `json:"displayName,omitempty"`
	IconLarge        *AbsolutePathBuf `json:"iconLarge,omitempty"`
	IconLargeURL     string           `json:"iconLargeUrl,omitempty"`
	IconSmall        *AbsolutePathBuf `json:"iconSmall,omitempty"`
	IconSmallURL     string           `json:"iconSmallUrl,omitempty"`
	ShortDescription string           `json:"shortDescription,omitempty"`
}

// ToolExposureSurface mirrors the upstream `ToolExposureSurface` enum.
type ToolExposureSurface string

const (
	ToolExposureSurfaceCodeMode ToolExposureSurface = "code_mode"
	ToolExposureSurfaceDeferred ToolExposureSurface = "deferred"
	ToolExposureSurfaceDirect   ToolExposureSurface = "direct"
)
