// Code generated by scripts/gen_go_types.py from the vendored codex schema. DO NOT EDIT.
//
// Source: internal/protocol/schema/codex_app_server_protocol.v2.schemas.json
// Filter: ^(Fs|Mcp|ListMcp|ConfigMcpServerReload)
//
// Regenerate: make generate-types

package schema

import "encoding/json"

// AbsolutePathBuf mirrors the upstream `AbsolutePathBuf` definition.
type AbsolutePathBuf = string

// FsChangedNotification mirrors the upstream `FsChangedNotification` definition.
type FsChangedNotification struct {
	ChangedPaths []AbsolutePathBuf `json:"changedPaths"`
	WatchID      string            `json:"watchId"`
}

// FsCopyParams mirrors the upstream `FsCopyParams` definition.
type FsCopyParams struct {
	DestinationPath AbsolutePathBuf `json:"destinationPath"`
	Recursive       bool            `json:"recursive,omitempty"`
	SourcePath      AbsolutePathBuf `json:"sourcePath"`
}

// FsCopyResponse mirrors the upstream `FsCopyResponse` definition.
type FsCopyResponse = struct{}

// FsCreateDirectoryParams mirrors the upstream `FsCreateDirectoryParams` definition.
type FsCreateDirectoryParams struct {
	Path      AbsolutePathBuf `json:"path"`
	Recursive bool            `json:"recursive,omitempty"`
}

// FsCreateDirectoryResponse mirrors the upstream `FsCreateDirectoryResponse` definition.
type FsCreateDirectoryResponse = struct{}

// FsGetMetadataParams mirrors the upstream `FsGetMetadataParams` definition.
type FsGetMetadataParams struct {
	Path AbsolutePathBuf `json:"path"`
}

// FsGetMetadataResponse mirrors the upstream `FsGetMetadataResponse` definition.
type FsGetMetadataResponse struct {
	CreatedAtMs  int64 `json:"createdAtMs"`
	IsDirectory  bool  `json:"isDirectory"`
	IsFile       bool  `json:"isFile"`
	IsSymlink    bool  `json:"isSymlink"`
	ModifiedAtMs int64 `json:"modifiedAtMs"`
}

// FsReadDirectoryEntry mirrors the upstream `FsReadDirectoryEntry` definition.
type FsReadDirectoryEntry struct {
	FileName    string `json:"fileName"`
	IsDirectory bool   `json:"isDirectory"`
	IsFile      bool   `json:"isFile"`
}

// FsReadDirectoryParams mirrors the upstream `FsReadDirectoryParams` definition.
type FsReadDirectoryParams struct {
	Path AbsolutePathBuf `json:"path"`
}

// FsReadDirectoryResponse mirrors the upstream `FsReadDirectoryResponse` definition.
type FsReadDirectoryResponse struct {
	Entries []FsReadDirectoryEntry `json:"entries"`
}

// FsReadFileParams mirrors the upstream `FsReadFileParams` definition.
type FsReadFileParams struct {
	Path AbsolutePathBuf `json:"path"`
}

// FsReadFileResponse mirrors the upstream `FsReadFileResponse` definition.
type FsReadFileResponse struct {
	DataBase64 string `json:"dataBase64"`
}

// FsRemoveParams mirrors the upstream `FsRemoveParams` definition.
type FsRemoveParams struct {
	Force     bool            `json:"force,omitempty"`
	Path      AbsolutePathBuf `json:"path"`
	Recursive bool            `json:"recursive,omitempty"`
}

// FsRemoveResponse mirrors the upstream `FsRemoveResponse` definition.
type FsRemoveResponse = struct{}

// FsUnwatchParams mirrors the upstream `FsUnwatchParams` definition.
type FsUnwatchParams struct {
	WatchID string `json:"watchId"`
}

// FsUnwatchResponse mirrors the upstream `FsUnwatchResponse` definition.
type FsUnwatchResponse = struct{}

// FsWatchParams mirrors the upstream `FsWatchParams` definition.
type FsWatchParams struct {
	Path    AbsolutePathBuf `json:"path"`
	WatchID string          `json:"watchId"`
}

// FsWatchResponse mirrors the upstream `FsWatchResponse` definition.
type FsWatchResponse struct {
	Path AbsolutePathBuf `json:"path"`
}

// FsWriteFileParams mirrors the upstream `FsWriteFileParams` definition.
type FsWriteFileParams struct {
	DataBase64 string          `json:"dataBase64"`
	Path       AbsolutePathBuf `json:"path"`
}

// FsWriteFileResponse mirrors the upstream `FsWriteFileResponse` definition.
type FsWriteFileResponse = struct{}

// ListMcpServerStatusParams mirrors the upstream `ListMcpServerStatusParams` definition.
type ListMcpServerStatusParams struct {
	Cursor     string                 `json:"cursor,omitempty"`
	Detail     *McpServerStatusDetail `json:"detail,omitempty"`
	Limit      int64                  `json:"limit,omitempty"`
	ServerName string                 `json:"serverName,omitempty"`
	ThreadID   string                 `json:"threadId,omitempty"`
}

// ListMcpServerStatusResponse mirrors the upstream `ListMcpServerStatusResponse` definition.
type ListMcpServerStatusResponse struct {
	Data       []McpServerStatus `json:"data"`
	NextCursor string            `json:"nextCursor,omitempty"`
}

// McpAppDisplayMode mirrors the upstream `McpAppDisplayMode` enum.
type McpAppDisplayMode string

const (
	McpAppDisplayModeInline     McpAppDisplayMode = "inline"
	McpAppDisplayModeFullscreen McpAppDisplayMode = "fullscreen"
)

// McpAppUi mirrors the upstream `McpAppUi` definition.
type McpAppUi struct {
	PreferredModelDisplayMode McpAppDisplayMode `json:"preferredModelDisplayMode"`
	ResourceURI               string            `json:"resourceUri"`
}

// McpAuthStatus mirrors the upstream `McpAuthStatus` enum.
type McpAuthStatus string

const (
	McpAuthStatusUnknown     McpAuthStatus = "unknown"
	McpAuthStatusUnsupported McpAuthStatus = "unsupported"
	McpAuthStatusNotLoggedIn McpAuthStatus = "notLoggedIn"
	McpAuthStatusBearerToken McpAuthStatus = "bearerToken"
	McpAuthStatusOAuth       McpAuthStatus = "oAuth"
)

// McpResourceReadParams mirrors the upstream `McpResourceReadParams` definition.
type McpResourceReadParams struct {
	ConnectorID  string                 `json:"connectorId,omitempty"`
	OriginCallID string                 `json:"originCallId,omitempty"`
	Server       string                 `json:"server"`
	Target       *McpResourceReadTarget `json:"target,omitempty"`
	ThreadID     string                 `json:"threadId,omitempty"`
	URI          string                 `json:"uri"`
}

// McpResourceReadResponse mirrors the upstream `McpResourceReadResponse` definition.
type McpResourceReadResponse struct {
	Contents     []ResourceContent `json:"contents"`
	OriginCallID string            `json:"originCallId,omitempty"`
}

// McpResourceReadTarget mirrors the upstream `McpResourceReadTarget` definition.
type McpResourceReadTarget struct {
	ConnectorID string `json:"connectorId"`
	LinkID      string `json:"linkId"`
}

// McpServerConnectionStatus mirrors the upstream `McpServerConnectionStatus` enum.
type McpServerConnectionStatus string

const (
	McpServerConnectionStatusNotStarted             McpServerConnectionStatus = "notStarted"
	McpServerConnectionStatusStarting               McpServerConnectionStatus = "starting"
	McpServerConnectionStatusConnected              McpServerConnectionStatus = "connected"
	McpServerConnectionStatusAuthenticationRequired McpServerConnectionStatus = "authenticationRequired"
	McpServerConnectionStatusFailed                 McpServerConnectionStatus = "failed"
	McpServerConnectionStatusCancelled              McpServerConnectionStatus = "cancelled"
	McpServerConnectionStatusDisabled               McpServerConnectionStatus = "disabled"
)

// McpServerEventNotification mirrors the upstream `McpServerEventNotification` definition.
type McpServerEventNotification struct {
	Method string          `json:"method"`
	Params json.RawMessage `json:"params"`
}

// McpServerEventStreamNotification mirrors the upstream `McpServerEventStreamNotification` definition.
type McpServerEventStreamNotification struct {
	Notification   McpServerEventNotification `json:"notification"`
	SubscriptionID string                     `json:"subscriptionId"`
}

// McpServerInfo mirrors the upstream `McpServerInfo` definition.
type McpServerInfo struct {
	Description string            `json:"description,omitempty"`
	Icons       []json.RawMessage `json:"icons,omitempty"`
	Name        string            `json:"name"`
	Title       string            `json:"title,omitempty"`
	Version     string            `json:"version"`
	WebsiteURL  string            `json:"websiteUrl,omitempty"`
}

// McpServerMigration mirrors the upstream `McpServerMigration` definition.
type McpServerMigration struct {
	Name string `json:"name"`
}

// McpServerOauthClientRegistration mirrors the upstream `McpServerOauthClientRegistration` enum.
type McpServerOauthClientRegistration string

const (
	McpServerOauthClientRegistrationAuto McpServerOauthClientRegistration = "auto"
	McpServerOauthClientRegistrationCimd McpServerOauthClientRegistration = "cimd"
	McpServerOauthClientRegistrationDcr  McpServerOauthClientRegistration = "dcr"
)

// McpServerOauthLoginCompletedNotification mirrors the upstream `McpServerOauthLoginCompletedNotification` definition.
type McpServerOauthLoginCompletedNotification struct {
	Error    string `json:"error,omitempty"`
	LoginID  string `json:"loginId,omitempty"`
	Name     string `json:"name"`
	Success  bool   `json:"success"`
	ThreadID string `json:"threadId,omitempty"`
}

// McpServerOauthLoginParams mirrors the upstream `McpServerOauthLoginParams` definition.
type McpServerOauthLoginParams struct {
	ClientRegistration *McpServerOauthClientRegistration `json:"clientRegistration,omitempty"`
	Name               string                            `json:"name"`
	Scopes             []string                          `json:"scopes,omitempty"`
	ThreadID           string                            `json:"threadId,omitempty"`
	TimeoutSecs        int64                             `json:"timeoutSecs,omitempty"`
}

// McpServerOauthLoginResponse mirrors the upstream `McpServerOauthLoginResponse` definition.
type McpServerOauthLoginResponse struct {
	AuthorizationURL string `json:"authorizationUrl"`
	LoginID          string `json:"loginId,omitempty"`
}

// McpServerRefreshResponse mirrors the upstream `McpServerRefreshResponse` definition.
type McpServerRefreshResponse = struct{}

// McpServerStartupFailureReason mirrors the upstream `McpServerStartupFailureReason` enum.
type McpServerStartupFailureReason string

const (
	McpServerStartupFailureReasonReauthenticationRequired McpServerStartupFailureReason = "reauthenticationRequired"
)

// McpServerStartupState mirrors the upstream `McpServerStartupState` enum.
type McpServerStartupState string

const (
	McpServerStartupStateStarting  McpServerStartupState = "starting"
	McpServerStartupStateReady     McpServerStartupState = "ready"
	McpServerStartupStateFailed    McpServerStartupState = "failed"
	McpServerStartupStateCancelled McpServerStartupState = "cancelled"
)

// McpServerStatus mirrors the upstream `McpServerStatus` definition.
type McpServerStatus struct {
	AuthStatus         McpAuthStatus              `json:"authStatus"`
	HTTPOrigin         string                     `json:"httpOrigin,omitempty"`
	Name               string                     `json:"name"`
	PluginID           string                     `json:"pluginId,omitempty"`
	ResourceTemplates  []ResourceTemplate         `json:"resourceTemplates"`
	Resources          []Resource                 `json:"resources"`
	RuntimeStatus      *McpServerConnectionStatus `json:"runtimeStatus,omitempty"`
	ServerCapabilities json.RawMessage            `json:"serverCapabilities,omitempty"`
	ServerInfo         *McpServerInfo             `json:"serverInfo,omitempty"`
	Tools              map[string]Tool            `json:"tools"`
	ToolsError         string                     `json:"toolsError,omitempty"`
}

// McpServerStatusDetail mirrors the upstream `McpServerStatusDetail` enum.
type McpServerStatusDetail string

const (
	McpServerStatusDetailFull             McpServerStatusDetail = "full"
	McpServerStatusDetailToolsAndAuthOnly McpServerStatusDetail = "toolsAndAuthOnly"
)

// McpServerStatusUpdatedNotification mirrors the upstream `McpServerStatusUpdatedNotification` definition.
type McpServerStatusUpdatedNotification struct {
	Error         string                         `json:"error,omitempty"`
	FailureReason *McpServerStartupFailureReason `json:"failureReason,omitempty"`
	Name          string                         `json:"name"`
	Status        McpServerStartupState          `json:"status"`
	ThreadID      string                         `json:"threadId,omitempty"`
}

// McpServerToolCallParams mirrors the upstream `McpServerToolCallParams` definition.
type McpServerToolCallParams struct {
	Meta      json.RawMessage `json:"_meta,omitempty"`
	Arguments json.RawMessage `json:"arguments,omitempty"`
	Server    string          `json:"server"`
	ThreadID  string          `json:"threadId"`
	Tool      string          `json:"tool"`
}

// McpServerToolCallResponse mirrors the upstream `McpServerToolCallResponse` definition.
type McpServerToolCallResponse struct {
	Meta              json.RawMessage   `json:"_meta,omitempty"`
	Content           []json.RawMessage `json:"content"`
	IsError           bool              `json:"isError,omitempty"`
	StructuredContent json.RawMessage   `json:"structuredContent,omitempty"`
}

// McpToolCallAppContext mirrors the upstream `McpToolCallAppContext` definition.
type McpToolCallAppContext struct {
	ActionName  string `json:"actionName,omitempty"`
	AppName     string `json:"appName,omitempty"`
	ConnectorID string `json:"connectorId"`
	LinkID      string `json:"linkId,omitempty"`
	ResourceURI string `json:"resourceUri,omitempty"`
}

// McpToolCallError mirrors the upstream `McpToolCallError` definition.
type McpToolCallError struct {
	Message string `json:"message"`
}

// McpToolCallProgressNotification mirrors the upstream `McpToolCallProgressNotification` definition.
type McpToolCallProgressNotification struct {
	ItemID   string `json:"itemId"`
	Message  string `json:"message"`
	ThreadID string `json:"threadId"`
	TurnID   string `json:"turnId"`
}

// McpToolCallResult mirrors the upstream `McpToolCallResult` definition.
type McpToolCallResult struct {
	Meta              json.RawMessage   `json:"_meta,omitempty"`
	Content           []json.RawMessage `json:"content"`
	StructuredContent json.RawMessage   `json:"structuredContent,omitempty"`
}

// McpToolCallStatus mirrors the upstream `McpToolCallStatus` enum.
type McpToolCallStatus string

const (
	McpToolCallStatusInProgress McpToolCallStatus = "inProgress"
	McpToolCallStatusCompleted  McpToolCallStatus = "completed"
	McpToolCallStatusFailed     McpToolCallStatus = "failed"
)

// Resource mirrors the upstream `Resource` definition.
type Resource struct {
	Meta        json.RawMessage   `json:"_meta,omitempty"`
	Annotations json.RawMessage   `json:"annotations,omitempty"`
	Description string            `json:"description,omitempty"`
	Icons       []json.RawMessage `json:"icons,omitempty"`
	MimeType    string            `json:"mimeType,omitempty"`
	Name        string            `json:"name"`
	Size        int64             `json:"size,omitempty"`
	Title       string            `json:"title,omitempty"`
	URI         string            `json:"uri"`
}

// ResourceContent mirrors the upstream `ResourceContent` definition.
type ResourceContent = json.RawMessage

// ResourceTemplate mirrors the upstream `ResourceTemplate` definition.
type ResourceTemplate struct {
	Annotations json.RawMessage `json:"annotations,omitempty"`
	Description string          `json:"description,omitempty"`
	MimeType    string          `json:"mimeType,omitempty"`
	Name        string          `json:"name"`
	Title       string          `json:"title,omitempty"`
	URITemplate string          `json:"uriTemplate"`
}

// Tool mirrors the upstream `Tool` definition.
type Tool struct {
	Meta         json.RawMessage   `json:"_meta,omitempty"`
	Annotations  json.RawMessage   `json:"annotations,omitempty"`
	Description  string            `json:"description,omitempty"`
	Icons        []json.RawMessage `json:"icons,omitempty"`
	InputSchema  json.RawMessage   `json:"inputSchema"`
	Name         string            `json:"name"`
	OutputSchema json.RawMessage   `json:"outputSchema,omitempty"`
	Title        string            `json:"title,omitempty"`
}
