package schema

// Code generated by tools/codexgen sync. DO NOT EDIT.
//
// Upstream Codex publishes no protocol version number (codex-rs/Cargo.toml is uniformly
// "0.0.0" and JSONRPC_VERSION in src/rpc.rs is dead code), so the anchor is the codex git
// commit plus the hashes of the vendored artifacts. The machine-readable surface lives in
// .codex-schema/manifest.json and gen/method-surface.json.
//
// Scope model: declared_stable == source methods WITHOUT #[experimental(...)]. The
// precomputed exports are used only for reconciliation -- in particular the export does
// NOT filter experimental ServerNotifications, so notifications can never be scoped by
// the export alone.

const (
	// SourceCodexCommit is the github.com/openai/codex commit all artifacts came from.
	SourceCodexCommit = "14c8b7771ab2b617a131f5d8e55e98d18e56ed09"

	// SchemaRevision is the sha256 of the vendored codex_app_server_protocol.v2.schemas.json
	// (the upstream *stable* aggregate; it excludes the 5 methods listed in
	// gen/export-exclusions.json).
	SchemaRevision = "9e39bb66909635ed7794878429e683a097d479b4a9bf969891642be23b797d74"

	// SchemaTitle mirrors the upstream aggregate's title for traceability.
	SchemaTitle = "Codex app-server protocol v2 (stable)"

	// DeclaredStable counts source methods WITHOUT an #[experimental] annotation, per face.
	DeclaredStableClientRequest      = 108
	DeclaredStableServerRequest      = 10
	DeclaredStableServerNotification = 63
	DeclaredStableClientNotification = 1

	// SourceExperimental counts methods annotated #[experimental], per face. These are
	// out of scope by decision R2 (see gen/not-in-scope.txt).
	SourceExperimentalClientRequest      = 65
	SourceExperimentalServerRequest      = 1
	SourceExperimentalServerNotification = 23
	SourceExperimentalClientNotification = 0

	// NotInScopeTotal is DeclaredStable's complement: every #[experimental] method.
	NotInScopeTotal = 89
)
