// Code generated by scripts/gen_go_client.py from gen/method-surface.json. DO NOT EDIT.
//
// Every generated binding is exercised against the mock server. The assertion is that
// the *wire method string* is the upstream one -- the one thing the coverage gate
// cannot verify on its own.

package codexgo_test

import (
	"context"
	"encoding/json"
	"reflect"
	"strings"
	"testing"
	"time"

	codexgo "github.com/zealbase/codex-app-server-go"
)

func TestGeneratedClientMethodsUseUpstreamWireMethods(t *testing.T) {
	cases := []struct {
		name   string
		wire   string
		invoke func(context.Context, *codexgo.Client) error
	}{
		{"Initialize", "initialize", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.Initialize(ctx, *new(codexgo.InitializeParams))
			return err
		}},
		{"ThreadStart", "thread/start", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadStart(ctx, *new(codexgo.ThreadStartParams))
			return err
		}},
		{"ThreadResume", "thread/resume", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadResume(ctx, *new(codexgo.ThreadResumeParams))
			return err
		}},
		{"ThreadFork", "thread/fork", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadFork(ctx, *new(codexgo.ThreadForkParams))
			return err
		}},
		{"ThreadArchive", "thread/archive", func(ctx context.Context, c *codexgo.Client) error {
			err := c.ThreadArchive(ctx, *new(codexgo.ThreadArchiveParams))
			return err
		}},
		{"ThreadDelete", "thread/delete", func(ctx context.Context, c *codexgo.Client) error {
			err := c.ThreadDelete(ctx, *new(codexgo.ThreadDeleteRequest))
			return err
		}},
		{"ThreadUnsubscribe", "thread/unsubscribe", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadUnsubscribe(ctx, *new(codexgo.ThreadUnsubscribeRequest))
			return err
		}},
		{"ThreadSetName", "thread/name/set", func(ctx context.Context, c *codexgo.Client) error {
			err := c.ThreadSetName(ctx, *new(codexgo.ThreadSetNameParams))
			return err
		}},
		{"ThreadGoalSet", "thread/goal/set", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadGoalSet(ctx, *new(codexgo.ThreadGoalSetRequest))
			return err
		}},
		{"ThreadGoalGet", "thread/goal/get", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadGoalGet(ctx, *new(codexgo.ThreadGoalGetRequest))
			return err
		}},
		{"ThreadGoalClear", "thread/goal/clear", func(ctx context.Context, c *codexgo.Client) error {
			err := c.ThreadGoalClear(ctx, *new(codexgo.ThreadGoalClearRequest))
			return err
		}},
		{"ThreadMetadataUpdate", "thread/metadata/update", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadMetadataUpdate(ctx, *new(codexgo.ThreadMetadataUpdateRequest))
			return err
		}},
		{"ThreadAttachmentAdd", "thread/attachment/add", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadAttachmentAdd(ctx, *new(codexgo.ThreadAttachmentAddParams))
			return err
		}},
		{"ThreadAttachmentList", "thread/attachment/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadAttachmentList(ctx, *new(codexgo.ThreadAttachmentListParams))
			return err
		}},
		{"ThreadAttachmentOwnerList", "thread/attachmentOwner/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadAttachmentOwnerList(ctx, *new(codexgo.ThreadAttachmentOwnerListParams))
			return err
		}},
		{"ThreadAttachmentRemove", "thread/attachment/remove", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadAttachmentRemove(ctx, *new(codexgo.ThreadAttachmentRemoveParams))
			return err
		}},
		{"ThreadSectionMove", "thread/section/move", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadSectionMove(ctx, *new(codexgo.ThreadSectionMoveParams))
			return err
		}},
		{"ThreadUnarchive", "thread/unarchive", func(ctx context.Context, c *codexgo.Client) error {
			err := c.ThreadUnarchive(ctx, *new(codexgo.ThreadUnarchiveParams))
			return err
		}},
		{"ThreadCompactStart", "thread/compact/start", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadCompactStart(ctx, *new(codexgo.ThreadCompactStartParams))
			return err
		}},
		{"ThreadShellCommand", "thread/shellCommand", func(ctx context.Context, c *codexgo.Client) error {
			err := c.ThreadShellCommand(ctx, *new(codexgo.ThreadShellCommandRequest))
			return err
		}},
		{"ThreadApproveGuardianDeniedAction", "thread/approveGuardianDeniedAction", func(ctx context.Context, c *codexgo.Client) error {
			err := c.ThreadApproveGuardianDeniedAction(ctx, *new(codexgo.ThreadApproveGuardianDeniedActionRequest))
			return err
		}},
		{"ThreadRevert", "thread/revert", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadRevert(ctx, *new(codexgo.ThreadRevertParams))
			return err
		}},
		{"ThreadList", "thread/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadList(ctx, *new(codexgo.ThreadListParams))
			return err
		}},
		{"ThreadSectionList", "threadSection/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadSectionList(ctx, *new(codexgo.ThreadSectionListParams))
			return err
		}},
		{"ThreadSectionCreate", "threadSection/create", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadSectionCreate(ctx, *new(codexgo.ThreadSectionCreateParams))
			return err
		}},
		{"ThreadSectionUpdate", "threadSection/update", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadSectionUpdate(ctx, *new(codexgo.ThreadSectionUpdateParams))
			return err
		}},
		{"ThreadSectionDelete", "threadSection/delete", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadSectionDelete(ctx, *new(codexgo.ThreadSectionDeleteParams))
			return err
		}},
		{"ThreadLoadedList", "thread/loaded/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadLoadedList(ctx)
			return err
		}},
		{"ThreadRead", "thread/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadRead(ctx, *new(codexgo.ThreadReadParams))
			return err
		}},
		{"ThreadTurnsList", "thread/turns/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadTurnsList(ctx, *new(codexgo.ThreadTurnsListParams))
			return err
		}},
		{"ThreadItemsList", "thread/items/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadItemsList(ctx, *new(codexgo.ThreadItemsListParams))
			return err
		}},
		{"ThreadInjectItems", "thread/inject_items", func(ctx context.Context, c *codexgo.Client) error {
			err := c.ThreadInjectItems(ctx, *new(codexgo.ThreadInjectItemsRequest))
			return err
		}},
		{"SkillsList", "skills/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.SkillsList(ctx, *new(codexgo.SkillsListRequest))
			return err
		}},
		{"SkillsExtraRootsSet", "skills/extraRoots/set", func(ctx context.Context, c *codexgo.Client) error {
			err := c.SkillsExtraRootsSet(ctx, *new(codexgo.SkillsExtraRootsSetRequest))
			return err
		}},
		{"HooksList", "hooks/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.HooksList(ctx, *new(codexgo.HooksListRequest))
			return err
		}},
		{"MarketplaceAdd", "marketplace/add", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.MarketplaceAdd(ctx, *new(codexgo.MarketplaceAddParams))
			return err
		}},
		{"MarketplaceRemove", "marketplace/remove", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.MarketplaceRemove(ctx, *new(codexgo.MarketplaceRemoveParams))
			return err
		}},
		{"MarketplaceUpgrade", "marketplace/upgrade", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.MarketplaceUpgrade(ctx, *new(codexgo.MarketplaceUpgradeParams))
			return err
		}},
		{"PluginList", "plugin/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PluginList(ctx, *new(codexgo.PluginListParams))
			return err
		}},
		{"PluginInstalled", "plugin/installed", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PluginInstalled(ctx, *new(codexgo.PluginInstalledParams))
			return err
		}},
		{"PluginReconcile", "plugin/reconcile", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PluginReconcile(ctx, *new(codexgo.PluginReconcileParams))
			return err
		}},
		{"PluginRead", "plugin/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PluginRead(ctx, *new(codexgo.PluginReadParams))
			return err
		}},
		{"PluginSkillRead", "plugin/skill/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PluginSkillRead(ctx, *new(codexgo.PluginSkillReadParams))
			return err
		}},
		{"PluginShareSave", "plugin/share/save", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PluginShareSave(ctx, *new(codexgo.PluginShareSaveParams))
			return err
		}},
		{"PluginShareUpdateTargets", "plugin/share/updateTargets", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PluginShareUpdateTargets(ctx, *new(codexgo.PluginShareUpdateTargetsParams))
			return err
		}},
		{"PluginShareList", "plugin/share/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PluginShareList(ctx, *new(codexgo.PluginShareListParams))
			return err
		}},
		{"PluginShareCheckout", "plugin/share/checkout", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PluginShareCheckout(ctx, *new(codexgo.PluginShareCheckoutParams))
			return err
		}},
		{"PluginShareDelete", "plugin/share/delete", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PluginShareDelete(ctx, *new(codexgo.PluginShareDeleteParams))
			return err
		}},
		{"AppsRead", "app/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.AppsRead(ctx, *new(codexgo.AppsReadParams))
			return err
		}},
		{"AppsList", "app/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.AppsList(ctx, *new(codexgo.AppsListParams))
			return err
		}},
		{"AppsInstalled", "app/installed", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.AppsInstalled(ctx, *new(codexgo.AppsInstalledParams))
			return err
		}},
		{"FSReadFile", "fs/readFile", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.FSReadFile(ctx, *new(codexgo.FsReadFileParams))
			return err
		}},
		{"FSWriteFile", "fs/writeFile", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.FSWriteFile(ctx, *new(codexgo.FsWriteFileParams))
			return err
		}},
		{"FSCreateDirectory", "fs/createDirectory", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.FSCreateDirectory(ctx, *new(codexgo.FsCreateDirectoryParams))
			return err
		}},
		{"FSGetMetadata", "fs/getMetadata", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.FSGetMetadata(ctx, *new(codexgo.FsGetMetadataParams))
			return err
		}},
		{"FSReadDirectory", "fs/readDirectory", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.FSReadDirectory(ctx, *new(codexgo.FsReadDirectoryParams))
			return err
		}},
		{"FSRemove", "fs/remove", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.FSRemove(ctx, *new(codexgo.FsRemoveParams))
			return err
		}},
		{"FSCopy", "fs/copy", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.FSCopy(ctx, *new(codexgo.FsCopyParams))
			return err
		}},
		{"FSWatch", "fs/watch", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.FSWatch(ctx, *new(codexgo.FsWatchParams))
			return err
		}},
		{"FSUnwatch", "fs/unwatch", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.FSUnwatch(ctx, *new(codexgo.FsUnwatchParams))
			return err
		}},
		{"SkillsConfigWrite", "skills/config/write", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.SkillsConfigWrite(ctx, *new(codexgo.SkillsConfigWriteRequest))
			return err
		}},
		{"PluginInstall", "plugin/install", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PluginInstall(ctx, *new(codexgo.PluginInstallParams))
			return err
		}},
		{"PluginUninstall", "plugin/uninstall", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PluginUninstall(ctx, *new(codexgo.PluginUninstallParams))
			return err
		}},
		{"TurnStart", "turn/start", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.TurnStart(ctx, *new(codexgo.TurnStartParams))
			return err
		}},
		{"TurnSteer", "turn/steer", func(ctx context.Context, c *codexgo.Client) error {
			err := c.TurnSteer(ctx, *new(codexgo.TurnSteerParams))
			return err
		}},
		{"TurnInterrupt", "turn/interrupt", func(ctx context.Context, c *codexgo.Client) error {
			err := c.TurnInterrupt(ctx, *new(codexgo.TurnInterruptParams))
			return err
		}},
		{"ReviewStart", "review/start", func(ctx context.Context, c *codexgo.Client) error {
			err := c.ReviewStart(ctx, *new(codexgo.ReviewStartParams))
			return err
		}},
		{"ModelList", "model/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ModelList(ctx, false)
			return err
		}},
		{"GatewayOAuthRead", "account/gatewayOAuth/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.GatewayOAuthRead(ctx)
			return err
		}},
		{"GatewayOAuthLogin", "account/gatewayOAuth/login", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.GatewayOAuthLogin(ctx)
			return err
		}},
		{"GatewayOAuthCancel", "account/gatewayOAuth/cancel", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.GatewayOAuthCancel(ctx)
			return err
		}},
		{"ModelProviderCapabilitiesRead", "modelProvider/capabilities/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ModelProviderCapabilitiesRead(ctx)
			return err
		}},
		{"ExperimentalFeatureList", "experimentalFeature/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ExperimentalFeatureList(ctx, *new(codexgo.ExperimentalFeatureListRequest))
			return err
		}},
		{"PermissionProfileList", "permissionProfile/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PermissionProfileList(ctx, *new(codexgo.PermissionProfileListParams))
			return err
		}},
		{"ExperimentalFeatureEnablementSet", "experimentalFeature/enablement/set", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ExperimentalFeatureEnablementSet(ctx, *new(codexgo.ExperimentalFeatureEnablementSetRequest))
			return err
		}},
		{"MCPServerOauthLogin", "mcpServer/oauth/login", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.MCPServerOauthLogin(ctx, *new(codexgo.McpServerOauthLoginParams))
			return err
		}},
		{"ConfigMCPServerReload", "config/mcpServer/reload", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ConfigMCPServerReload(ctx)
			return err
		}},
		{"MCPServerStatusList", "mcpServerStatus/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.MCPServerStatusList(ctx, *new(codexgo.ListMcpServerStatusParams))
			return err
		}},
		{"MCPServerResourceRead", "mcpServer/resource/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.MCPServerResourceRead(ctx, *new(codexgo.McpResourceReadParams))
			return err
		}},
		{"MCPServerToolCall", "mcpServer/tool/call", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.MCPServerToolCall(ctx, *new(codexgo.McpServerToolCallParams))
			return err
		}},
		{"WindowsSandboxSetupStart", "windowsSandbox/setupStart", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.WindowsSandboxSetupStart(ctx, *new(codexgo.WindowsSandboxSetupStartParams))
			return err
		}},
		{"WindowsSandboxReadiness", "windowsSandbox/readiness", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.WindowsSandboxReadiness(ctx)
			return err
		}},
		{"LoginAPIKey", "account/login/start", func(ctx context.Context, c *codexgo.Client) error {
			err := c.LoginAPIKey(ctx, "")
			return err
		}},
		{"CancelLoginAccount", "account/login/cancel", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.CancelLoginAccount(ctx, *new(codexgo.CancelLoginAccountParams))
			return err
		}},
		{"Logout", "account/logout", func(ctx context.Context, c *codexgo.Client) error {
			err := c.Logout(ctx)
			return err
		}},
		{"GetAccountRateLimits", "account/rateLimits/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.GetAccountRateLimits(ctx, *new(codexgo.NullableGetAccountRateLimitsParams))
			return err
		}},
		{"ConsumeAccountRateLimitResetCredit", "account/rateLimitResetCredit/consume", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ConsumeAccountRateLimitResetCredit(ctx, *new(codexgo.ConsumeAccountRateLimitResetCreditParams))
			return err
		}},
		{"GetAccountTokenUsage", "account/usage/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.GetAccountTokenUsage(ctx, *new(codexgo.NullableGetAccountTokenUsageParams))
			return err
		}},
		{"GetWorkspaceMessages", "account/workspaceMessages/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.GetWorkspaceMessages(ctx)
			return err
		}},
		{"SendAddCreditsNudgeEmail", "account/sendAddCreditsNudgeEmail", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.SendAddCreditsNudgeEmail(ctx, *new(codexgo.SendAddCreditsNudgeEmailParams))
			return err
		}},
		{"FeedbackUpload", "feedback/upload", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.FeedbackUpload(ctx, *new(codexgo.FeedbackUploadParams))
			return err
		}},
		{"CommandExec", "command/exec", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.CommandExec(ctx, *new(codexgo.CommandExecRequest))
			return err
		}},
		{"CommandExecWrite", "command/exec/write", func(ctx context.Context, c *codexgo.Client) error {
			err := c.CommandExecWrite(ctx, *new(codexgo.CommandExecWriteRequest))
			return err
		}},
		{"CommandExecTerminate", "command/exec/terminate", func(ctx context.Context, c *codexgo.Client) error {
			err := c.CommandExecTerminate(ctx, *new(codexgo.CommandExecTerminateRequest))
			return err
		}},
		{"CommandExecResize", "command/exec/resize", func(ctx context.Context, c *codexgo.Client) error {
			err := c.CommandExecResize(ctx, *new(codexgo.CommandExecResizeRequest))
			return err
		}},
		{"ConfigRead", "config/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ConfigRead(ctx, *new(codexgo.ConfigReadRequest))
			return err
		}},
		{"ExternalAgentConfigDetect", "externalAgentConfig/detect", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ExternalAgentConfigDetect(ctx, *new(codexgo.ExternalAgentConfigDetectParams))
			return err
		}},
		{"ExternalAgentConfigImport", "externalAgentConfig/import", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ExternalAgentConfigImport(ctx, *new(codexgo.ExternalAgentConfigImportParams))
			return err
		}},
		{"ExternalAgentConfigImportHistoryRecord", "externalAgentConfig/import/recordHistory", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ExternalAgentConfigImportHistoryRecord(ctx, *new(codexgo.ExternalAgentConfigImportHistoryRecordParams))
			return err
		}},
		{"ExternalAgentConfigImportHistoriesRead", "externalAgentConfig/import/readHistories", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ExternalAgentConfigImportHistoriesRead(ctx)
			return err
		}},
		{"ConfigValueWrite", "config/value/write", func(ctx context.Context, c *codexgo.Client) error {
			err := c.ConfigValueWrite(ctx, *new(codexgo.ConfigValueWriteRequest))
			return err
		}},
		{"ConfigBatchWrite", "config/batchWrite", func(ctx context.Context, c *codexgo.Client) error {
			err := c.ConfigBatchWrite(ctx, *new(codexgo.ConfigBatchWriteRequest))
			return err
		}},
		{"ConfigRequirementsRead", "configRequirements/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ConfigRequirementsRead(ctx)
			return err
		}},
		{"AccountRead", "account/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.AccountRead(ctx)
			return err
		}},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			client, mock := newClientFromMock(t)
			defer client.Close()

			var got json.RawMessage
			mock.Handle(tc.wire, func(params json.RawMessage) (any, error) {
				got = params
				return map[string]any{}, nil
			})

			if err := tc.invoke(testCtx(t), client); err != nil {
				t.Fatalf("%s: %v", tc.wire, err)
			}
			// A params-less method legitimately sends nothing; everything else must
			// reach the handler with a body.
			if len(got) == 0 && tc.wire != "" {
				t.Logf("%s: handler received no params (method may take none)", tc.wire)
			}
		})
	}
}

// Notification decoders: a stable notification must decode into its modelled event
// type, not silently fall through to RawNotificationEvent.
func TestGeneratedNotificationDecoders(t *testing.T) {
	cases := []struct {
		wire      string
		eventType string
	}{
		{"account/login/completed", "LoginCompleted"},
		{"account/rateLimits/updated", "AccountRateLimitsUpdatedEvent"},
		{"account/updated", "AccountUpdatedEvent"},
		{"app/list/updated", "AppListUpdatedEvent"},
		{"command/exec/outputDelta", "CommandExecOutputDeltaEvent"},
		{"configWarning", "ConfigWarningEvent"},
		{"deprecationNotice", "DeprecationNoticeEvent"},
		{"error", "ErrorEvent"},
		{"externalAgentConfig/import/completed", "ExternalAgentConfigImportCompletedEvent"},
		{"externalAgentConfig/import/progress", "ExternalAgentConfigImportProgressEvent"},
		{"fs/changed", "FsChangedEvent"},
		{"guardianWarning", "GuardianWarningEvent"},
		{"hook/completed", "HookCompletedEvent"},
		{"hook/started", "HookStartedEvent"},
		{"item/agentMessage/delta", "ItemAgentMessageDeltaEvent"},
		{"item/autoApprovalReview/completed", "ItemAutoApprovalReviewCompletedEvent"},
		{"item/autoApprovalReview/started", "ItemAutoApprovalReviewStartedEvent"},
		{"item/commandExecution/outputDelta", "ItemCommandExecutionOutputDeltaEvent"},
		{"item/commandExecution/terminalInteraction", "TerminalInteractionEvent"},
		{"item/completed", "ItemCompletedEvent"},
		{"item/fileChange/outputDelta", "ItemFileChangeOutputDeltaEvent"},
		{"item/fileChange/patchUpdated", "ItemFileChangePatchUpdatedEvent"},
		{"item/mcpToolCall/progress", "McpToolCallProgressEvent"},
		{"item/plan/delta", "ItemPlanDeltaEvent"},
		{"item/reasoning/summaryPartAdded", "ItemReasoningSummaryPartAddedEvent"},
		{"item/reasoning/summaryTextDelta", "ItemReasoningSummaryTextDeltaEvent"},
		{"item/reasoning/textDelta", "ItemReasoningTextDeltaEvent"},
		{"item/started", "ItemStartedEvent"},
		{"mcpServer/oauthLogin/completed", "McpServerOauthLoginCompletedEvent"},
		{"mcpServer/startupStatus/updated", "McpServerStatusUpdatedEvent"},
		{"model/rerouted", "ModelReroutedEvent"},
		{"model/verification", "ModelVerificationEvent"},
		{"rawResponseItem/completed", "RawResponseItemCompletedEvent"},
		{"remoteControl/status/changed", "RemoteControlStatusChangedEvent"},
		{"serverRequest/resolved", "ServerRequestResolvedEvent"},
		{"skills/changed", "SkillsChangedEvent"},
		{"thread/archived", "ThreadArchivedEvent"},
		{"thread/closed", "ThreadClosedEvent"},
		{"thread/compacted", "ThreadCompactedEvent"},
		{"thread/deleted", "ThreadDeletedEvent"},
		{"thread/goal/cleared", "ThreadGoalClearedEvent"},
		{"thread/goal/updated", "ThreadGoalUpdatedEvent"},
		{"thread/name/updated", "ThreadNameUpdatedEvent"},
		{"thread/started", "ThreadStartedEvent"},
		{"thread/status/changed", "ThreadStatusChangedEvent"},
		{"thread/tokenUsage/updated", "ThreadTokenUsageUpdatedEvent"},
		{"thread/unarchived", "ThreadUnarchivedEvent"},
		{"turn/completed", "TurnCompletedEvent"},
		{"turn/diff/updated", "TurnDiffUpdatedEvent"},
		{"turn/plan/updated", "TurnPlanUpdatedEvent"},
		{"turn/started", "TurnStartedEvent"},
		{"warning", "WarningEvent"},
		{"windows/worldWritableWarning", "WindowsWorldWritableWarningEvent"},
		{"windowsSandbox/setupCompleted", "WindowsSandboxSetupCompletedEvent"},
	}

	for _, tc := range cases {
		t.Run(tc.wire, func(t *testing.T) {
			client, mock := newClientFromMock(t)
			defer client.Close()

			sub := client.Events()
			defer sub.Close()
			time.Sleep(20 * time.Millisecond)

			if err := mock.Notify(tc.wire, map[string]any{"threadId": "thr-1", "turnId": "turn-1"}); err != nil {
				t.Fatalf("Notify: %v", err)
			}

			select {
			case ev := <-sub.C():
				// reflect prints a package-qualified name (codexgo.Foo, protocol.Bar);
				// strip the qualifier so the assertion is about the type itself.
				got := reflect.TypeOf(ev.Value).String()
				if i := strings.LastIndex(got, "."); i >= 0 {
					got = got[i+1:]
				}
				if got != tc.eventType {
					t.Fatalf("decoded to %s, want %s", got, tc.eventType)
				}
			case <-time.After(3 * time.Second):
				t.Fatalf("timeout waiting for %s", tc.wire)
			}
		})
	}
}
