// Code generated by scripts/gen_go_client.py from gen/method-surface.json. DO NOT EDIT.
//
// Typed bindings for stable client requests that had no hand-written method. Method
// and type names come from the upstream Rust variant/type names. Regenerate with
// `make generate-client`.

package codexgo

import (
	"context"

	"github.com/zealbase/codex-app-server-go/internal/protocol"
	schematypes "github.com/zealbase/codex-app-server-go/internal/protocol/schema"
)

// Type aliases for params/response types the root package did not yet expose.
type (
	CancelLoginAccountParams = schematypes.CancelLoginAccountParams
	CancelLoginAccountResponse = schematypes.CancelLoginAccountResponse
	ConfigRequirementsReadResponse = schematypes.ConfigRequirementsReadResponse
	ConsumeAccountRateLimitResetCreditParams = schematypes.ConsumeAccountRateLimitResetCreditParams
	ConsumeAccountRateLimitResetCreditResponse = schematypes.ConsumeAccountRateLimitResetCreditResponse
	ExternalAgentConfigDetectParams = schematypes.ExternalAgentConfigDetectParams
	ExternalAgentConfigDetectResponse = schematypes.ExternalAgentConfigDetectResponse
	ExternalAgentConfigImportHistoriesReadResponse = schematypes.ExternalAgentConfigImportHistoriesReadResponse
	ExternalAgentConfigImportHistoryRecordParams = schematypes.ExternalAgentConfigImportHistoryRecordParams
	ExternalAgentConfigImportHistoryRecordResponse = schematypes.ExternalAgentConfigImportHistoryRecordResponse
	ExternalAgentConfigImportParams = schematypes.ExternalAgentConfigImportParams
	ExternalAgentConfigImportResponse = schematypes.ExternalAgentConfigImportResponse
	FeedbackUploadParams = schematypes.FeedbackUploadParams
	FeedbackUploadResponse = schematypes.FeedbackUploadResponse
	FuzzyFileSearchParams = schematypes.FuzzyFileSearchParams
	GatewayOAuthCancelResponse = schematypes.GatewayOAuthCancelResponse
	GatewayOAuthLoginResponse = schematypes.GatewayOAuthLoginResponse
	GatewayOAuthReadResponse = schematypes.GatewayOAuthReadResponse
	GetAccountRateLimitsResponse = schematypes.GetAccountRateLimitsResponse
	GetAccountTokenUsageResponse = schematypes.GetAccountTokenUsageResponse
	GetWorkspaceMessagesResponse = schematypes.GetWorkspaceMessagesResponse
	NullableGetAccountRateLimitsParams = schematypes.NullableGetAccountRateLimitsParams
	NullableGetAccountTokenUsageParams = schematypes.NullableGetAccountTokenUsageParams
	PermissionProfileListParams = schematypes.PermissionProfileListParams
	PermissionProfileListResponse = schematypes.PermissionProfileListResponse
	SendAddCreditsNudgeEmailParams = schematypes.SendAddCreditsNudgeEmailParams
	SendAddCreditsNudgeEmailResponse = schematypes.SendAddCreditsNudgeEmailResponse
	ThreadAttachmentAddParams = schematypes.ThreadAttachmentAddParams
	ThreadAttachmentAddResponse = schematypes.ThreadAttachmentAddResponse
	ThreadAttachmentListParams = schematypes.ThreadAttachmentListParams
	ThreadAttachmentListResponse = schematypes.ThreadAttachmentListResponse
	ThreadAttachmentOwnerListParams = schematypes.ThreadAttachmentOwnerListParams
	ThreadAttachmentOwnerListResponse = schematypes.ThreadAttachmentOwnerListResponse
	ThreadAttachmentRemoveParams = schematypes.ThreadAttachmentRemoveParams
	ThreadAttachmentRemoveResponse = schematypes.ThreadAttachmentRemoveResponse
	ThreadCompactStartParams = schematypes.ThreadCompactStartParams
	ThreadCompactStartResponse = schematypes.ThreadCompactStartResponse
	ThreadItemsListParams = schematypes.ThreadItemsListParams
	ThreadItemsListResponse = schematypes.ThreadItemsListResponse
	ThreadSectionCreateParams = schematypes.ThreadSectionCreateParams
	ThreadSectionCreateResponse = schematypes.ThreadSectionCreateResponse
	ThreadSectionDeleteParams = schematypes.ThreadSectionDeleteParams
	ThreadSectionDeleteResponse = schematypes.ThreadSectionDeleteResponse
	ThreadSectionListParams = schematypes.ThreadSectionListParams
	ThreadSectionListResponse = schematypes.ThreadSectionListResponse
	ThreadSectionMoveParams = schematypes.ThreadSectionMoveParams
	ThreadSectionMoveResponse = schematypes.ThreadSectionMoveResponse
	ThreadSectionUpdateParams = schematypes.ThreadSectionUpdateParams
	ThreadSectionUpdateResponse = schematypes.ThreadSectionUpdateResponse
	ThreadTurnsListParams = schematypes.ThreadTurnsListParams
	ThreadTurnsListResponse = schematypes.ThreadTurnsListResponse
	WindowsSandboxReadinessResponse = schematypes.WindowsSandboxReadinessResponse
	WindowsSandboxSetupStartParams = schematypes.WindowsSandboxSetupStartParams
	WindowsSandboxSetupStartResponse = schematypes.WindowsSandboxSetupStartResponse
)

// ThreadAttachmentAdd calls `thread/attachment/add`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ThreadAttachmentAdd(ctx context.Context, req ThreadAttachmentAddParams) (ThreadAttachmentAddResponse, error) {
	var resp ThreadAttachmentAddResponse
	if err := c.transport.Call(ctx, protocol.MethodThreadAttachmentAdd, req, &resp); err != nil {
		return ThreadAttachmentAddResponse{}, err
	}
	return resp, nil
}

// ThreadAttachmentList calls `thread/attachment/list`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ThreadAttachmentList(ctx context.Context, req ThreadAttachmentListParams) (ThreadAttachmentListResponse, error) {
	var resp ThreadAttachmentListResponse
	if err := c.transport.Call(ctx, protocol.MethodThreadAttachmentList, req, &resp); err != nil {
		return ThreadAttachmentListResponse{}, err
	}
	return resp, nil
}

// ThreadAttachmentOwnerList calls `thread/attachmentOwner/list`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ThreadAttachmentOwnerList(ctx context.Context, req ThreadAttachmentOwnerListParams) (ThreadAttachmentOwnerListResponse, error) {
	var resp ThreadAttachmentOwnerListResponse
	if err := c.transport.Call(ctx, protocol.MethodThreadAttachmentOwnerList, req, &resp); err != nil {
		return ThreadAttachmentOwnerListResponse{}, err
	}
	return resp, nil
}

// ThreadAttachmentRemove calls `thread/attachment/remove`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ThreadAttachmentRemove(ctx context.Context, req ThreadAttachmentRemoveParams) (ThreadAttachmentRemoveResponse, error) {
	var resp ThreadAttachmentRemoveResponse
	if err := c.transport.Call(ctx, protocol.MethodThreadAttachmentRemove, req, &resp); err != nil {
		return ThreadAttachmentRemoveResponse{}, err
	}
	return resp, nil
}

// ThreadSectionMove calls `thread/section/move`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ThreadSectionMove(ctx context.Context, req ThreadSectionMoveParams) (ThreadSectionMoveResponse, error) {
	var resp ThreadSectionMoveResponse
	if err := c.transport.Call(ctx, protocol.MethodThreadSectionMove, req, &resp); err != nil {
		return ThreadSectionMoveResponse{}, err
	}
	return resp, nil
}

// ThreadCompactStart calls `thread/compact/start`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ThreadCompactStart(ctx context.Context, req ThreadCompactStartParams) (ThreadCompactStartResponse, error) {
	var resp ThreadCompactStartResponse
	if err := c.transport.Call(ctx, protocol.MethodThreadCompact, req, &resp); err != nil {
		return ThreadCompactStartResponse{}, err
	}
	return resp, nil
}

// ThreadSectionList calls `threadSection/list`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ThreadSectionList(ctx context.Context, req ThreadSectionListParams) (ThreadSectionListResponse, error) {
	var resp ThreadSectionListResponse
	if err := c.transport.Call(ctx, protocol.MethodThreadSectionList, req, &resp); err != nil {
		return ThreadSectionListResponse{}, err
	}
	return resp, nil
}

// ThreadSectionCreate calls `threadSection/create`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ThreadSectionCreate(ctx context.Context, req ThreadSectionCreateParams) (ThreadSectionCreateResponse, error) {
	var resp ThreadSectionCreateResponse
	if err := c.transport.Call(ctx, protocol.MethodThreadSectionCreate, req, &resp); err != nil {
		return ThreadSectionCreateResponse{}, err
	}
	return resp, nil
}

// ThreadSectionUpdate calls `threadSection/update`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ThreadSectionUpdate(ctx context.Context, req ThreadSectionUpdateParams) (ThreadSectionUpdateResponse, error) {
	var resp ThreadSectionUpdateResponse
	if err := c.transport.Call(ctx, protocol.MethodThreadSectionUpdate, req, &resp); err != nil {
		return ThreadSectionUpdateResponse{}, err
	}
	return resp, nil
}

// ThreadSectionDelete calls `threadSection/delete`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ThreadSectionDelete(ctx context.Context, req ThreadSectionDeleteParams) (ThreadSectionDeleteResponse, error) {
	var resp ThreadSectionDeleteResponse
	if err := c.transport.Call(ctx, protocol.MethodThreadSectionDelete, req, &resp); err != nil {
		return ThreadSectionDeleteResponse{}, err
	}
	return resp, nil
}

// ThreadTurnsList calls `thread/turns/list`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ThreadTurnsList(ctx context.Context, req ThreadTurnsListParams) (ThreadTurnsListResponse, error) {
	var resp ThreadTurnsListResponse
	if err := c.transport.Call(ctx, protocol.MethodThreadTurnsList, req, &resp); err != nil {
		return ThreadTurnsListResponse{}, err
	}
	return resp, nil
}

// ThreadItemsList calls `thread/items/list`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ThreadItemsList(ctx context.Context, req ThreadItemsListParams) (ThreadItemsListResponse, error) {
	var resp ThreadItemsListResponse
	if err := c.transport.Call(ctx, protocol.MethodThreadItemsList, req, &resp); err != nil {
		return ThreadItemsListResponse{}, err
	}
	return resp, nil
}

// GatewayOAuthRead calls `account/gatewayOAuth/read`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) GatewayOAuthRead(ctx context.Context) (GatewayOAuthReadResponse, error) {
	var resp GatewayOAuthReadResponse
	if err := c.transport.Call(ctx, protocol.MethodGatewayOAuthRead, nil, &resp); err != nil {
		return GatewayOAuthReadResponse{}, err
	}
	return resp, nil
}

// GatewayOAuthLogin calls `account/gatewayOAuth/login`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) GatewayOAuthLogin(ctx context.Context) (GatewayOAuthLoginResponse, error) {
	var resp GatewayOAuthLoginResponse
	if err := c.transport.Call(ctx, protocol.MethodGatewayOAuthLogin, nil, &resp); err != nil {
		return GatewayOAuthLoginResponse{}, err
	}
	return resp, nil
}

// GatewayOAuthCancel calls `account/gatewayOAuth/cancel`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) GatewayOAuthCancel(ctx context.Context) (GatewayOAuthCancelResponse, error) {
	var resp GatewayOAuthCancelResponse
	if err := c.transport.Call(ctx, protocol.MethodGatewayOAuthCancel, nil, &resp); err != nil {
		return GatewayOAuthCancelResponse{}, err
	}
	return resp, nil
}

// PermissionProfileList calls `permissionProfile/list`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) PermissionProfileList(ctx context.Context, req PermissionProfileListParams) (PermissionProfileListResponse, error) {
	var resp PermissionProfileListResponse
	if err := c.transport.Call(ctx, protocol.MethodPermissionProfileList, req, &resp); err != nil {
		return PermissionProfileListResponse{}, err
	}
	return resp, nil
}

// WindowsSandboxSetupStart calls `windowsSandbox/setupStart`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) WindowsSandboxSetupStart(ctx context.Context, req WindowsSandboxSetupStartParams) (WindowsSandboxSetupStartResponse, error) {
	var resp WindowsSandboxSetupStartResponse
	if err := c.transport.Call(ctx, protocol.MethodWindowsSandboxSetupStart, req, &resp); err != nil {
		return WindowsSandboxSetupStartResponse{}, err
	}
	return resp, nil
}

// WindowsSandboxReadiness calls `windowsSandbox/readiness`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) WindowsSandboxReadiness(ctx context.Context) (WindowsSandboxReadinessResponse, error) {
	var resp WindowsSandboxReadinessResponse
	if err := c.transport.Call(ctx, protocol.MethodWindowsSandboxReadiness, nil, &resp); err != nil {
		return WindowsSandboxReadinessResponse{}, err
	}
	return resp, nil
}

// CancelLoginAccount calls `account/login/cancel`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) CancelLoginAccount(ctx context.Context, req CancelLoginAccountParams) (CancelLoginAccountResponse, error) {
	var resp CancelLoginAccountResponse
	if err := c.transport.Call(ctx, protocol.MethodAccountLoginCancel, req, &resp); err != nil {
		return CancelLoginAccountResponse{}, err
	}
	return resp, nil
}

// GetAccountRateLimits calls `account/rateLimits/read`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) GetAccountRateLimits(ctx context.Context, req NullableGetAccountRateLimitsParams) (GetAccountRateLimitsResponse, error) {
	var resp GetAccountRateLimitsResponse
	if err := c.transport.Call(ctx, protocol.MethodGetAccountRateLimits, req, &resp); err != nil {
		return GetAccountRateLimitsResponse{}, err
	}
	return resp, nil
}

// ConsumeAccountRateLimitResetCredit calls `account/rateLimitResetCredit/consume`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ConsumeAccountRateLimitResetCredit(ctx context.Context, req ConsumeAccountRateLimitResetCreditParams) (ConsumeAccountRateLimitResetCreditResponse, error) {
	var resp ConsumeAccountRateLimitResetCreditResponse
	if err := c.transport.Call(ctx, protocol.MethodConsumeAccountRateLimitResetCredit, req, &resp); err != nil {
		return ConsumeAccountRateLimitResetCreditResponse{}, err
	}
	return resp, nil
}

// GetAccountTokenUsage calls `account/usage/read`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) GetAccountTokenUsage(ctx context.Context, req NullableGetAccountTokenUsageParams) (GetAccountTokenUsageResponse, error) {
	var resp GetAccountTokenUsageResponse
	if err := c.transport.Call(ctx, protocol.MethodGetAccountTokenUsage, req, &resp); err != nil {
		return GetAccountTokenUsageResponse{}, err
	}
	return resp, nil
}

// GetWorkspaceMessages calls `account/workspaceMessages/read`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) GetWorkspaceMessages(ctx context.Context) (GetWorkspaceMessagesResponse, error) {
	var resp GetWorkspaceMessagesResponse
	if err := c.transport.Call(ctx, protocol.MethodGetWorkspaceMessages, nil, &resp); err != nil {
		return GetWorkspaceMessagesResponse{}, err
	}
	return resp, nil
}

// SendAddCreditsNudgeEmail calls `account/sendAddCreditsNudgeEmail`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) SendAddCreditsNudgeEmail(ctx context.Context, req SendAddCreditsNudgeEmailParams) (SendAddCreditsNudgeEmailResponse, error) {
	var resp SendAddCreditsNudgeEmailResponse
	if err := c.transport.Call(ctx, protocol.MethodSendAddCreditsNudgeEmail, req, &resp); err != nil {
		return SendAddCreditsNudgeEmailResponse{}, err
	}
	return resp, nil
}

// FeedbackUpload calls `feedback/upload`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) FeedbackUpload(ctx context.Context, req FeedbackUploadParams) (FeedbackUploadResponse, error) {
	var resp FeedbackUploadResponse
	if err := c.transport.Call(ctx, protocol.MethodFeedbackUpload, req, &resp); err != nil {
		return FeedbackUploadResponse{}, err
	}
	return resp, nil
}

// ExternalAgentConfigDetect calls `externalAgentConfig/detect`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ExternalAgentConfigDetect(ctx context.Context, req ExternalAgentConfigDetectParams) (ExternalAgentConfigDetectResponse, error) {
	var resp ExternalAgentConfigDetectResponse
	if err := c.transport.Call(ctx, protocol.MethodExternalAgentConfigDetect, req, &resp); err != nil {
		return ExternalAgentConfigDetectResponse{}, err
	}
	return resp, nil
}

// ExternalAgentConfigImport calls `externalAgentConfig/import`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ExternalAgentConfigImport(ctx context.Context, req ExternalAgentConfigImportParams) (ExternalAgentConfigImportResponse, error) {
	var resp ExternalAgentConfigImportResponse
	if err := c.transport.Call(ctx, protocol.MethodExternalAgentConfigImport, req, &resp); err != nil {
		return ExternalAgentConfigImportResponse{}, err
	}
	return resp, nil
}

// ExternalAgentConfigImportHistoryRecord calls `externalAgentConfig/import/recordHistory`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ExternalAgentConfigImportHistoryRecord(ctx context.Context, req ExternalAgentConfigImportHistoryRecordParams) (ExternalAgentConfigImportHistoryRecordResponse, error) {
	var resp ExternalAgentConfigImportHistoryRecordResponse
	if err := c.transport.Call(ctx, protocol.MethodExternalAgentConfigImportHistoryRecord, req, &resp); err != nil {
		return ExternalAgentConfigImportHistoryRecordResponse{}, err
	}
	return resp, nil
}

// ExternalAgentConfigImportHistoriesRead calls `externalAgentConfig/import/readHistories`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ExternalAgentConfigImportHistoriesRead(ctx context.Context) (ExternalAgentConfigImportHistoriesReadResponse, error) {
	var resp ExternalAgentConfigImportHistoriesReadResponse
	if err := c.transport.Call(ctx, protocol.MethodExternalAgentConfigImportHistoriesRead, nil, &resp); err != nil {
		return ExternalAgentConfigImportHistoriesReadResponse{}, err
	}
	return resp, nil
}

// ConfigRequirementsRead calls `configRequirements/read`.
//
// Generated binding. See gen/method-surface.json for the authoritative surface.
func (c *Client) ConfigRequirementsRead(ctx context.Context) (ConfigRequirementsReadResponse, error) {
	var resp ConfigRequirementsReadResponse
	if err := c.transport.Call(ctx, protocol.MethodConfigRequirementsRead, nil, &resp); err != nil {
		return ConfigRequirementsReadResponse{}, err
	}
	return resp, nil
}
