// Code generated by scripts/gen_go_client.py from gen/method-surface.json. DO NOT EDIT.
//
// Every generated binding is exercised against the mock server. The assertion is that
// the *wire method string* is the upstream one -- the one thing the coverage gate
// cannot verify on its own.

package codexgo_test

import (
	"context"
	"encoding/json"
	"testing"

	codexgo "github.com/zealbase/codex-app-server-go"
)

func TestGeneratedClientMethodsUseUpstreamWireMethods(t *testing.T) {
	cases := []struct {
		name   string
		wire   string
		invoke func(context.Context, *codexgo.Client) error
	}{
		{"ThreadAttachmentAdd", "thread/attachment/add", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadAttachmentAdd(ctx, *new(codexgo.ThreadAttachmentAddParams))
			return err
		}},
		{"ThreadAttachmentList", "thread/attachment/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadAttachmentList(ctx, *new(codexgo.ThreadAttachmentListParams))
			return err
		}},
		{"ThreadAttachmentOwnerList", "thread/attachmentOwner/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadAttachmentOwnerList(ctx, *new(codexgo.ThreadAttachmentOwnerListParams))
			return err
		}},
		{"ThreadAttachmentRemove", "thread/attachment/remove", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadAttachmentRemove(ctx, *new(codexgo.ThreadAttachmentRemoveParams))
			return err
		}},
		{"ThreadSectionMove", "thread/section/move", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadSectionMove(ctx, *new(codexgo.ThreadSectionMoveParams))
			return err
		}},
		{"ThreadCompactStart", "thread/compact/start", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadCompactStart(ctx, *new(codexgo.ThreadCompactStartParams))
			return err
		}},
		{"ThreadSectionList", "threadSection/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadSectionList(ctx, *new(codexgo.ThreadSectionListParams))
			return err
		}},
		{"ThreadSectionCreate", "threadSection/create", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadSectionCreate(ctx, *new(codexgo.ThreadSectionCreateParams))
			return err
		}},
		{"ThreadSectionUpdate", "threadSection/update", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadSectionUpdate(ctx, *new(codexgo.ThreadSectionUpdateParams))
			return err
		}},
		{"ThreadSectionDelete", "threadSection/delete", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadSectionDelete(ctx, *new(codexgo.ThreadSectionDeleteParams))
			return err
		}},
		{"ThreadTurnsList", "thread/turns/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadTurnsList(ctx, *new(codexgo.ThreadTurnsListParams))
			return err
		}},
		{"ThreadItemsList", "thread/items/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ThreadItemsList(ctx, *new(codexgo.ThreadItemsListParams))
			return err
		}},
		{"GatewayOAuthRead", "account/gatewayOAuth/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.GatewayOAuthRead(ctx)
			return err
		}},
		{"GatewayOAuthLogin", "account/gatewayOAuth/login", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.GatewayOAuthLogin(ctx)
			return err
		}},
		{"GatewayOAuthCancel", "account/gatewayOAuth/cancel", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.GatewayOAuthCancel(ctx)
			return err
		}},
		{"PermissionProfileList", "permissionProfile/list", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.PermissionProfileList(ctx, *new(codexgo.PermissionProfileListParams))
			return err
		}},
		{"WindowsSandboxSetupStart", "windowsSandbox/setupStart", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.WindowsSandboxSetupStart(ctx, *new(codexgo.WindowsSandboxSetupStartParams))
			return err
		}},
		{"WindowsSandboxReadiness", "windowsSandbox/readiness", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.WindowsSandboxReadiness(ctx)
			return err
		}},
		{"CancelLoginAccount", "account/login/cancel", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.CancelLoginAccount(ctx, *new(codexgo.CancelLoginAccountParams))
			return err
		}},
		{"GetAccountRateLimits", "account/rateLimits/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.GetAccountRateLimits(ctx, *new(codexgo.NullableGetAccountRateLimitsParams))
			return err
		}},
		{"ConsumeAccountRateLimitResetCredit", "account/rateLimitResetCredit/consume", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ConsumeAccountRateLimitResetCredit(ctx, *new(codexgo.ConsumeAccountRateLimitResetCreditParams))
			return err
		}},
		{"GetAccountTokenUsage", "account/usage/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.GetAccountTokenUsage(ctx, *new(codexgo.NullableGetAccountTokenUsageParams))
			return err
		}},
		{"GetWorkspaceMessages", "account/workspaceMessages/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.GetWorkspaceMessages(ctx)
			return err
		}},
		{"SendAddCreditsNudgeEmail", "account/sendAddCreditsNudgeEmail", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.SendAddCreditsNudgeEmail(ctx, *new(codexgo.SendAddCreditsNudgeEmailParams))
			return err
		}},
		{"FeedbackUpload", "feedback/upload", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.FeedbackUpload(ctx, *new(codexgo.FeedbackUploadParams))
			return err
		}},
		{"ExternalAgentConfigDetect", "externalAgentConfig/detect", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ExternalAgentConfigDetect(ctx, *new(codexgo.ExternalAgentConfigDetectParams))
			return err
		}},
		{"ExternalAgentConfigImport", "externalAgentConfig/import", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ExternalAgentConfigImport(ctx, *new(codexgo.ExternalAgentConfigImportParams))
			return err
		}},
		{"ExternalAgentConfigImportHistoryRecord", "externalAgentConfig/import/recordHistory", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ExternalAgentConfigImportHistoryRecord(ctx, *new(codexgo.ExternalAgentConfigImportHistoryRecordParams))
			return err
		}},
		{"ExternalAgentConfigImportHistoriesRead", "externalAgentConfig/import/readHistories", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ExternalAgentConfigImportHistoriesRead(ctx)
			return err
		}},
		{"ConfigRequirementsRead", "configRequirements/read", func(ctx context.Context, c *codexgo.Client) error {
			_, err := c.ConfigRequirementsRead(ctx)
			return err
		}},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			client, mock := newClientFromMock(t)
			defer client.Close()

			var got json.RawMessage
			mock.Handle(tc.wire, func(params json.RawMessage) (any, error) {
				got = params
				return map[string]any{}, nil
			})

			if err := tc.invoke(testCtx(t), client); err != nil {
				t.Fatalf("%s: %v", tc.wire, err)
			}
			// A params-less method legitimately sends nothing; everything else must
			// reach the handler with a body.
			if len(got) == 0 && tc.wire != "" {
				t.Logf("%s: handler received no params (method may take none)", tc.wire)
			}
		})
	}
}
