// Code generated by `go run ./tools/codexgen gen-client`. DO NOT EDIT.
//
// Method constants for stable client requests that envelope.go did not yet declare.
// Regenerate with `make generate-client`.

package protocol

const (
	MethodAuthRecoveryCompleted                  = "modelProvider/authRecoveryCompleted"
	MethodAuthRecoveryStarted                    = "modelProvider/authRecoveryStarted"
	MethodChatgptAuthTokensRefresh               = "account/chatgptAuthTokens/refresh"
	MethodConfigRequirementsRead                 = "configRequirements/read"
	MethodConsumeAccountRateLimitResetCredit     = "account/rateLimitResetCredit/consume"
	MethodExternalAgentConfigDetect              = "externalAgentConfig/detect"
	MethodExternalAgentConfigImport              = "externalAgentConfig/import"
	MethodExternalAgentConfigImportHistoriesRead = "externalAgentConfig/import/readHistories"
	MethodExternalAgentConfigImportHistoryRecord = "externalAgentConfig/import/recordHistory"
	MethodFeedbackUpload                         = "feedback/upload"
	MethodFuzzyFileSearch                        = "fuzzyFileSearch"
	MethodFuzzyFileSearchSessionCompleted        = "fuzzyFileSearch/sessionCompleted"
	MethodFuzzyFileSearchSessionUpdated          = "fuzzyFileSearch/sessionUpdated"
	MethodGatewayOAuthCancel                     = "account/gatewayOAuth/cancel"
	MethodGatewayOAuthChanged                    = "account/gatewayOAuth/changed"
	MethodGatewayOAuthLogin                      = "account/gatewayOAuth/login"
	MethodGatewayOAuthRead                       = "account/gatewayOAuth/read"
	MethodGetAccountRateLimits                   = "account/rateLimits/read"
	MethodGetAccountTokenUsage                   = "account/usage/read"
	MethodGetWorkspaceMessages                   = "account/workspaceMessages/read"
	MethodModelSafetyBufferingUpdated            = "model/safetyBuffering/updated"
	MethodPermissionProfileList                  = "permissionProfile/list"
	MethodSendAddCreditsNudgeEmail               = "account/sendAddCreditsNudgeEmail"
	MethodThreadAttachmentAdd                    = "thread/attachment/add"
	MethodThreadAttachmentList                   = "thread/attachment/list"
	MethodThreadAttachmentOwnerList              = "thread/attachmentOwner/list"
	MethodThreadAttachmentRemove                 = "thread/attachment/remove"
	MethodThreadAttachmentUpdated                = "thread/attachment/updated"
	MethodThreadItemsList                        = "thread/items/list"
	MethodThreadReverted                         = "thread/reverted"
	MethodThreadSectionCreate                    = "threadSection/create"
	MethodThreadSectionDelete                    = "threadSection/delete"
	MethodThreadSectionList                      = "threadSection/list"
	MethodThreadSectionMove                      = "thread/section/move"
	MethodThreadSectionUpdate                    = "threadSection/update"
	MethodThreadTurnsList                        = "thread/turns/list"
	MethodWindowsSandboxReadiness                = "windowsSandbox/readiness"
	MethodWindowsSandboxSetupStart               = "windowsSandbox/setupStart"
)
