// Code generated by scripts/gen_go_client.py. DO NOT EDIT.
//
// Method constants for stable client requests that envelope.go did not yet declare.
// Regenerate with `make generate-client`.

package protocol

const (
	MethodConfigRequirementsRead                 = "configRequirements/read"
	MethodConsumeAccountRateLimitResetCredit     = "account/rateLimitResetCredit/consume"
	MethodExternalAgentConfigDetect              = "externalAgentConfig/detect"
	MethodExternalAgentConfigImport              = "externalAgentConfig/import"
	MethodExternalAgentConfigImportHistoriesRead = "externalAgentConfig/import/readHistories"
	MethodExternalAgentConfigImportHistoryRecord = "externalAgentConfig/import/recordHistory"
	MethodFeedbackUpload                         = "feedback/upload"
	MethodFuzzyFileSearch                        = "fuzzyFileSearch"
	MethodGatewayOAuthCancel                     = "account/gatewayOAuth/cancel"
	MethodGatewayOAuthLogin                      = "account/gatewayOAuth/login"
	MethodGatewayOAuthRead                       = "account/gatewayOAuth/read"
	MethodGetAccountRateLimits                   = "account/rateLimits/read"
	MethodGetAccountTokenUsage                   = "account/usage/read"
	MethodGetWorkspaceMessages                   = "account/workspaceMessages/read"
	MethodPermissionProfileList                  = "permissionProfile/list"
	MethodSendAddCreditsNudgeEmail               = "account/sendAddCreditsNudgeEmail"
	MethodThreadAttachmentAdd                    = "thread/attachment/add"
	MethodThreadAttachmentList                   = "thread/attachment/list"
	MethodThreadAttachmentOwnerList              = "thread/attachmentOwner/list"
	MethodThreadAttachmentRemove                 = "thread/attachment/remove"
	MethodThreadItemsList                        = "thread/items/list"
	MethodThreadSectionCreate                    = "threadSection/create"
	MethodThreadSectionDelete                    = "threadSection/delete"
	MethodThreadSectionList                      = "threadSection/list"
	MethodThreadSectionMove                      = "thread/section/move"
	MethodThreadSectionUpdate                    = "threadSection/update"
	MethodThreadTurnsList                        = "thread/turns/list"
	MethodWindowsSandboxReadiness                = "windowsSandbox/readiness"
	MethodWindowsSandboxSetupStart               = "windowsSandbox/setupStart"
)
